### ISSUE TITLE
[SCH] Excog and Lustrate

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#104]
Similar to the Sage Taurochole/Druochole combo, can the Excog/Lustrate combo be inverted?  Currently, Lustrate becomes Excog when the latter is off CD, but there _are_ situations when Excog is off CD and you would not want to use it on a target you need to oGCD heal (for example, a DPS that needs a quick top-off but isn't likely to drop under 50% to trigger the Excog thereafter).

When the Sage combos were being implemented, the argument was made that there were situations where you'd want to use Druochole even when Taurochole was off CD, but the inverse was not true (you'd never want to try to use Taurochole over Druochole when the former is on CD, obviously).  As a result, the Sage combo was constructed so that Taurochole _falls back_ to Druochole when on CD, rather than Druochole _upgrading_ to Taurochole when not on CD, as this allowed the Sage to have both Taurochole and Druochole on their bars, so they could use the latter for spot healing when they don't want to waste the Tauro CD.

Can the same logic be applied to Excog and Lustrate?  ie. have Excog fall back to Lustrate when it is on CD, leaving Lustrate itself alone.  This would allow you to have Lustrate on your bar independently from Excog for spot healing when you don't want to waste the Excog cooldown.

**Comment by daemitus** [comment]
done
