### ISSUE TITLE
[RPR] Bug: Scythe/Harvest Moon feature

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#108]
With this combo enabled as well as the Scythe->Guillotine feature, if you have Soul Reaver stacks, Harvest Moon is still preferred over Guillotine, wasting the Soul Reaver stacks in the process.  When both of these features are enabled, Guillotine should be preferred, since Soul Reaver stacks are removed if you cast anything _except_ Gibbet, Gallows, or Guillotine.

To replicate, enable both the Scythe Harvest Moon Feature and the Scythe Guillotine feature, put up Soulsow, and then use Soul Slice -> Gluttony (or either of the other Reaver generators) -> Slice button.  This is most noticeable when entering combat with a trash pull with >50 Soul Gauge, as you can (without this bug) immediately go into Gluttony -> Guillotine -> Guillotine (to get Gluttony's CD rolling) before using Harvest Moon.

**Comment by daemitus** [comment]
will be shifted to after guillotine.
