### ISSUE TITLE
[GNB] Toggle option for No Mercy Double Down feature

### ISSUE THREAD

**Issue by SashaFFXIV** [daemitus/XIVComboPlugin#109]
Can you add a toggle to the No Mercy Double Down feature so that it replaces No Mercy with Double Down while No Mercy is active regardless of the cooldown of Double Down and how many cartridges you have? Being able to see Double Down's cooldown before you actually use it makes it a lot easier to actually use on time. Unless you remember the exact cooldown of Double Down by heart you'll often end up delaying it by 1 GCD because you can't see the CD until it's available.

**Comment by daemitus** [comment]
added an option to replace NM with DD, conflicting with the bow-shock/sonic-break feature. Due to it always replacing, it will never transition to BS/SB.

**Comment by Grammernatzi** [comment]
I would additionally say, if you want to use both features, just put Double Down on a cooldown bar or such. I have one for each class for cooldown actions that I don't keep on my bar (because they replace other actions).
