### ISSUE TITLE
[DNC] Flourish Proc Saver

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#110]
The Flourish Proc Saver exists to prevent you from overwriting procs by using Flourish.  However, it has several issues:

* The replacement logic is always active, making it impossible to see Flourish's remaining cooldown if you have a GCD proc.
* The GCD procs have priority over Fan Dance IV, despite it being impossible for a Fan Dance IV proc to be active and Flourish to be off CD.
* There's no way to merge Fan Dance IV into Flourish, following the logic of Devilment/Starfall Dance, without also merging the GCD procs onto it.

As such, I'd like to request that the Flourish Proc Save mechanism for procs _other than Fan Dance IV_ only be enabled when Flourish is off CD, as that's the only time the proc saver is serving its purpose of avoiding proc overwriting.  This fixes the issue of Fan Dance IV not being prioritized, as well as ensures you can see the cooldown of Flourish at all times (well, except when Fan Dance IV is up, but Fan Dance IV expires 30s before Flourish comes back off CD, if not used sooner).  I'd also like an option to _only_ merge Fan Dance IV into Flourish and not the other procs (I rather enjoy having to track the procs and having the risk of overwriting them, but I don't really like having Fan Dance IV on my bar when it's directly enabled by and mutually exclusive with Flourish), but making the proc saver only active (except for Fan Dance IV) when Flourish is off CD is the primary ask.

**Comment by daemitus** [comment]
Not that I raided with this originally, but my idea was I hit flourish, then I hit a GCD, then I hit fan4. Or you can try to double-weave flourish into fan4.

**Comment by daemitus** [comment]
fountainfall > fan4 > rev-casc > fan3 is the priority order

**Comment by daemitus** [comment]
Flourish now only changes when off-cd. Might be worthwhile to make it when less than 3 seconds? on-cd. 

Flourish Fan4 only feat added..

**Comment by kaedys** [comment]
I guess it depends on how many users are using this intentionally in preparation for Flourish, versus using it merely as a dummy-proof gate.  Personally, I doubt most peeps were using their Flourish button as their "I have a proc, use it!" button, and that this feature more served as a "I was silly and forgot to burn off (or just generate) that Flourishing Symmetry proc before trying to use Flourish" gating check.  Sure as heck what it was for me.

As for usage with Flourish, a _huge_ chunk of the time I was finding myself using it as Tech Step -> Devilment -> Saber Dance (avoids other procs) -> Flourish -> Fan 3 (or 4) -> Tillana -> Fan 4 (or 3) -> other stuff.  I imagine that Starfall Dance, when I get it (Dancer is currently 88.5), will either slot in in place of that Saber Dance, or after it, or after the Tillana.  In either case, I'd be using both Fan 3 and Fan 4 before using any of the GCD procs.
