### ISSUE TITLE
Reaper: Guillotine feature

### ISSUE THREAD

**Issue by BeetleLord** [daemitus/XIVComboPlugin#118]
I'll admit that I am not yet an expert on Reaper gameplay, but the following idea for a feature seems sensible to me:

Upon using Grim Swathe, Gibbet/Gallows are replaced with Guillotine until it is used (or Soul Reaver is lost).

This would save a dedicated hotkey space for Guillotine, and I don't think there are any sensible situations where you'd want to behave otherwise.

**Comment by daemitus** [comment]
cant check the difference between stalk and swathe being used. Just use the
existing combo to replace scythe with guillotine.

**Comment by Grammernatzi** [comment]
On top of that, what would you do if you used Gluttony, instead? Since you use it in both single-target and AoE

**Comment by BeetleLord** [comment]
> On top of that, what would you do if you used Gluttony, instead? Since you use it in both single-target and AoE

Hmm, you're right. The scythe -> guillotine combo that was recommended works fine.
