### ISSUE TITLE
[BRD] Iron Jaw Feature not working anymore

### ISSUE THREAD

**Issue by xinput** [daemitus/XIVComboPlugin#120]
2 Days ago I noticed, that the Iron Jaw feature seems to not working anymore. It doesn't replace Iron Jaw with Caustic Bite or Stormbite.

**Comment by kaedys** [comment]
I submitted a PR for a fix, looks like the conditional is checking the Pre Iron Jaws Feature instead.  In the mean time, I've confirmed in-game that if you select the Pre Iron Jaws Feature, it will work for now, as the conditional logic that should be behind the Iron Jaws Feature is behind the Pre-Iron-Jaws one instead atm.
