### ISSUE TITLE
[DRK] Replace Living Shadow with Shadowbringer when Living Shadow is active

### ISSUE THREAD

**Issue by SashaFFXIV** [daemitus/XIVComboPlugin#123]
Your uses of Shadowbringer are generally pooled until your two minutes with Living Shadow, so this makes sense. The main downside is not being able to use 1 stack of Shadowbringer in your last 60s buff window before the boss dies, but if Living Shadow is the button that gets replaced then you can have a separate Shadowbringer button that you can hit if you need to do that.

**Comment by daemitus** [comment]
I've added two different shadowbringer/shadow features. Please try them out and let me know your feedback.

**Comment by SashaFFXIV** [comment]
Missing Shadow Feature works great, but Living Shadow Feature does not work. It replaces Living Shadow with Shadowbringer regardless of whether your Shadow is active or not.

**Comment by daemitus** [comment]
I was checking the shadow timer >= 0 instead of > 0. should be fixed.
