### ISSUE TITLE
[Bug] [WHM] 'Solace into Misery' Feature also turns Cure II into Misery

### ISSUE THREAD

**Issue by SashaFFXIV** [daemitus/XIVComboPlugin#124]
https://i.imgur.com/zOYy4Vd.png

https://i.imgur.com/6aE6gub.png

This should either be removed or split into a separate option.

**Comment by daemitus** [comment]
You are correct. The misery feature should be dependent on the cure2 to rapture feature. I'll push this shortly.

**Comment by SashaFFXIV** [comment]
Issue fixed but this seems to have caused another bug. 'Rapture into Misery' is no longer functional.

https://i.imgur.com/4P2O0I1.png

https://i.imgur.com/d5iZ5UJ.png

**Comment by daemitus** [comment]
Can you check this again? I cant replicate the problem. Drag the action on to your bar fresh.

**Comment by SashaFFXIV** [comment]
Still happening even after dragging the action back on to the bar. The 'Holy into Misery' feature is also broken for me, apparently.

**Comment by daemitus** [comment]
found it. im dumb. fixed.

**Comment by SashaFFXIV** [comment]
Seems to have caused yet another bug. Solace, Rapture, Holy, Medica and Cure II all turn into Misery with 1 stack of Blood Lily when 3 stacks are required to cast.

![image](https://user-images.githubusercontent.com/55117631/153789125-43c7c84d-2e1e-4e5b-883d-2f4b248cd9fa.png)

**Comment by daemitus** [comment]
and here I thought I figured it out.

**Comment by daemitus** [comment]
Reverted to what it was a few days ago. I'll look into this again in a day or two.

**Comment by daemitus** [comment]
Ok. with what ive got running right now, I can't replicate this. Hit me on discord and I can take a look at whats going on if you'll stream the game, but otherwise I can't do anything else here.

**Comment by daemitus** [comment]
Rather, everything appears to work correctly, based on the description in the setup window.

**Comment by SashaFFXIV** [comment]
Yea I noticed that too. Everything is working for me now. It's possible I was doing something wrong or had an old version somehow.

**Comment by daemitus** [comment]
good to hear  :D
