### ISSUE TITLE
[AST] Minor Arcana/Crown Play bug

### ISSUE THREAD

**Issue by DenL** [daemitus/XIVComboPlugin#125]
Hello, there is currently a bug where

1. Checking "Minor Arcana to Crown Play Feature" does nothing, and
2. Checking "Crown Play to Minor Arcana Feature" actually does what 1 supposed to do.

I would like to use 2 instead, would greatly appreciate a fix, thank you!

**Comment by daemitus** [comment]
fixed. new version available shortly.
