### ISSUE TITLE
[MNK] Dragon Balance breaking rotations between lvl 50 - 59

### ISSUE THREAD

**Issue by LazzyWazzy** [daemitus/XIVComboPlugin#126]
I noticed that the Dragon Balance option for Monk would activate even when Masterful Blitz isn't unlocked after using balance and using the skills that would typically give you beast chakras. When you have the Dragon Kick/ Bootshine feature on like I do, this basically cripples you and forces you to deactivate the Dragon Balance feature in the middle of battle.

**Comment by LazzyWazzy** [comment]
I just realized this bug applies to the Monk Aoe Combo feature as well

**Comment by daemitus** [comment]
I've added some additional level checks. Please report back if this fixes
the issue, got some errands to run this morning and couldn't test.

**Comment by LazzyWazzy** [comment]
Yup, it fixed it. Thanks!
