### ISSUE TITLE
Suggestion: Summon Bahamut into Searing Light

### ISSUE THREAD

**Issue by Astorsoft** [daemitus/XIVComboPlugin#127]
Hi, not sure what is expected for suggestions, hope raising an issue for it is ok.

Suggestion: Searing Bahamut Feature
Change Summon Bahamut into Searing Light if both Searing Light and Summon Bahamut are off cooldown.

Rationale:

It is a common mistake to forget/fail casting Searing Light before casting Summon Bahamut and once Bahamut is out it is impossible to cast Searing Light, the best course of action is then to wait until the next Bahamut/Phoenix phase, ie: losing one minute on the timer.

**Comment by daemitus** [comment]
Will be available soon. I added a check that you are in combat, since searing can only be cast in combat. Feels like its the best way to handle it if you just wanted to cast baha outside combat in the overworld or something.

**Comment by Grammernatzi** [comment]
> Will be available soon. I added a check that you are in combat, since searing can only be cast in combat. Feels like its the best way to handle it if you just wanted to cast baha outside combat in the overworld or something.

That's probably unnecessary, Summon Bahamut/Dreadwyrm/etc requires being in combat as well.

**Comment by daemitus** [comment]
actually you can cast summon baha outside of combat. but it initiates
combat since he does an attack.
