### ISSUE TITLE
[WAR] Warrior suggestion for AoEs

### ISSUE THREAD

**Issue by 0kie** [daemitus/XIVComboPlugin#129]
Add an option to not change Mythril Tempest into Overpower when you do not have a target.
Just a qol option to make hitting everything when pulling easier

**Comment by kaedys** [comment]
Alternatively, swap the AoE combo so Overpower upgrades into Mythril Tempest.  Either works, though.  Having access to uncomboed Mythril Tempest _is_ quite useful when making AoE pulls.

**Comment by daemitus** [comment]
Added an option to stick on tempest when you have no target.

Should be available soon.
