### ISSUE TITLE
[PLD] Suggestion: Shield Bash -> Low Blow when Low Blow is off cooldown.

### ISSUE THREAD

**Issue by alphaONE2** [daemitus/XIVComboPlugin#130]
I've been using MOAction to do this for some time, and it's been nice having that hotbar slot back, but the lack of visual feedback showing which action is actually going to be used is slightly annoying. Having this in XIVCombo would solve that.

It's pretty much always preferable to use Low Blow to stun when it's available, since Shield Bash is on the GCD. Shield Bash does deal damage at 100 potency, and stuns for 1s longer than Low Blow, but the 1s is pretty much meaningless, and the damage is worse than every other GCD action PLD has available except Shield Lob, so you would never use it for damage.

**Comment by AkiraChisaka** [comment]
Yeah seems like a good feature, I second this.

**Comment by BeetleLord** [comment]
I concur, seems like a good idea. Shield Bash is barely worth a button on its own so this is a great way to deal with it.

**Comment by daemitus** [comment]
Available soon
