### ISSUE TITLE
[RDM] Weird Suggestion: Change Veraero 3 also to Melee Finisher Spells

### ISSUE THREAD

**Issue by AkiraChisaka** [daemitus/XIVComboPlugin#131]
So currently, you usually have 3 spells for Black and White mana.
![image](https://user-images.githubusercontent.com/47231500/153990103-bb12fdf9-ecab-421f-8718-6e79fe61d919.png)

After you finish 3 melee hits, it looks like this:
![image](https://user-images.githubusercontent.com/47231500/153990172-79b44de5-2421-4819-bf17-b1bf021f4a2d.png)

But after you use Verholy, it looks like this:
![image](https://user-images.githubusercontent.com/47231500/153990216-c353b92c-1038-4db7-a595-9e52880b31af.png)

I just feel that it looks a bit... unbalanced, and I really want the Veraero in the middle to also change to Scorch and Resolution.

**Comment by AkiraChisaka** [comment]
The solution is probably to just copy this:

```csharp
internal class RedMageVeraero2Verthunder2 : CustomCombo
    {
        protected internal override CustomComboPreset Preset { get; } = CustomComboPreset.RedMageAoECombo;

        protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
        {
            if (actionID == RDM.Veraero2 || actionID == RDM.Verthunder2)
            {
                if (lastComboMove == RDM.Scorch && level >= RDM.Levels.Resolution)
                    return RDM.Resolution;

                if ((lastComboMove == RDM.Verflare || lastComboMove == RDM.Verholy) && level >= RDM.Levels.Scorch)
                    return RDM.Scorch;

                if (level >= RDM.Levels.Scatter && (HasEffect(RDM.Buffs.Dualcast) || HasEffect(RDM.Buffs.Acceleration) || HasEffect(RDM.Buffs.Swiftcast) || HasEffect(RDM.Buffs.LostChainspell)))
                    return OriginalHook(RDM.Scatter);
            }

            return actionID;
        }
    }
```

And make it also apply to Aero 3 and Thunder 3.

**Comment by daemitus** [comment]
Added a "capstone" feature for veraero/verthunder (1 and 3) to do the resolution scorch holy/flare dance.

**Comment by AkiraChisaka** [comment]
Thanks Dae!
