### ISSUE TITLE
[RDM] Issue: "Acceleration into Swiftcast" Option Forces Swift to be used while Accel is Avaliable.

### ISSUE THREAD

**Issue by AkiraChisaka** [daemitus/XIVComboPlugin#136]
So, I tried turning on this option today, and this is what I observe.
![image](https://user-images.githubusercontent.com/47231500/154583001-b85a3a9c-f65b-4379-b8ef-b0d001758a98.png)

The Alt-E button here should be Accel, however, when both Accel and Swift are off CD, Accel is being overwritten by Swift.

I feel like the intended behaviour is to only have Accel be overwritten by Swift when Accel have no charges left...? Otherwise the "Acceleration into Swiftcast first" seems kinda useless.

Anyway, I feel like "Acceleration into Swiftcast" is being implemented as "Acceleration into Swiftcast first" now, and the latter option seems to not do anything.

**Comment by Grammernatzi** [comment]
No, this is intended because swiftcast is a damage cooldown and you need to keep its cooldown rolling at all times as Red Mage. The only time acceleration should take priority is if it is full on charges.

**Comment by Grammernatzi** [comment]
Upon looking at how it's coded, yes, the option isn't working. However, it's worth noting that you do want to use swiftcast over acceleration if acceleration isn't full on charges. The option is instead for swiftcast to take priority if they are both off cooldown and acceleration is full on charges, but it seems to just do that by default.

**Comment by daemitus** [comment]
lol. the option does nothing.

**Comment by Grammernatzi** [comment]
Is it intended to do nothing or is that just a bug?

**Comment by daemitus** [comment]
bugs for everybody

**Comment by daemitus** [comment]
wrapping the first block in the option does handles all the concerns i believe.
```
                    if (IsEnabled(CustomComboPreset.RedMageAccelerationSwiftcastOption))
                    {
                        if (IsOffCooldown(RDM.Acceleration) && IsOffCooldown(RDM.Swiftcast))
                            return RDM.Swiftcast;
                    }
```

**Comment by AkiraChisaka** [comment]
Thanks for the quick fix!
