### ISSUE TITLE
[RDM] Minor Bug: Impact overwrites Holy when AOE Combo option is turned on

### ISSUE THREAD

**Issue by AkiraChisaka** [daemitus/XIVComboPlugin#141]
So currently, when Aero 2 can be overwritten by Impact, Holy also get overwritten by Impact.

So after combo, button 3 should be Aero 2, and now it's Holy.

![image](https://user-images.githubusercontent.com/47231500/155068440-ef21d110-d9eb-4607-bf3e-5f3bde1d8587.png)

But when you use Swiftcast or Accelerate, Holy gets overwritten by Impact.

![image](https://user-images.githubusercontent.com/47231500/155068554-bbe6db1b-9cf4-409d-a4a0-2973457b22cd.png)

I don't think this is intended behavior, since you probably never want to cast Impact when you could be casting Holy.

Weird issue tho.

**Comment by daemitus** [comment]
fix coming down the pipe

**Comment by AkiraChisaka** [comment]
Ayy thanks!
