### ISSUE TITLE
[PLD] "Confiteor Feature" no longer working.

### ISSUE THREAD

**Issue by AboveAzureSkies** [daemitus/XIVComboPlugin#142]
Version: 1.3.2.26

Holy Spirit and Holy Circle are no longer replaced by Confiteor when Requiscat is up and only one stack remains, nor when MP is under 2000.

![image](https://user-images.githubusercontent.com/6124746/155077766-c23a13a2-6ee4-43f0-946f-44a2f4a4c4c2.png)

**Comment by Grammernatzi** [comment]
Does it still do this upon restart, changing class, etc? Sometimes things bug out. The code hasn't been touched for the feature.

**Comment by AboveAzureSkies** [comment]
Worked on uninstall and reinstall. 🤷‍♀️

**Comment by daemitus** [comment]
thanks for checking back in. its a known issue with how combo loads/unloads sometimes.
