### ISSUE TITLE
[SGE] Feature request: Toxikon into Phlegma

### ISSUE THREAD

**Issue by SashaFFXIV** [daemitus/XIVComboPlugin#145]
Currently with the 'Phlegma into Toxikon' Feature if you are out of Phlegma charges it is impossible to see the remaining cooldown of those charges. If Toxikon was the changed ability then you would be able to have a separate Phlegma button on the side to see the remaining cooldown while out of charges.

On a side note, how do you build this plugin from VStudio? I cloned the repo and downloaded the FFXIVClientStructs dependency but whenever I build I get this error. ![image](https://user-images.githubusercontent.com/55117631/155669645-5eb47e54-34fe-4349-bd13-9b6a374556c0.png)

**Comment by daemitus** [comment]
copy the build log output, the DLL merge failed

**Comment by SashaFFXIV** [comment]
[Output-Build.txt](https://github.com/daemitus/XIVComboPlugin/files/8145380/Output-Build.txt)

**Comment by daemitus** [comment]
3>System.IO.DirectoryNotFoundException: Could not find a part of the
path 'C:\Users\Davon\Documents\Github
Repositories\XIVComboPlugin-master\XIVComboExpanded\Repositories\XIVComboPlugin-master\XIVComboExpanded\bin\Release\XIVComboExpanded.dll


Something to do with your output path maybe.

**Comment by SashaFFXIV** [comment]
Yea that path is definitely messed up, should be 'C:\Users\Davon\Documents\Github
Repositories\XIVComboPlugin-master\XIVComboExpanded\bin\Release\XIVComboExpanded.dll'. I have no idea how to change that so I just changed the repo folder from 'Github Repositories' to 'Repositories' and it works now. Looks like the DLL merge is using a hard-coded file path.

**Comment by SashaFFXIV** [comment]
It also looks like the output path does not change to the output path you set in VStudio. Super simple band-aid fix is to add this at the bottom of XIVComboExpanded.csproj

```
	<Target Name="CopyCustomContent" AfterTargets="AfterBuild">
		<Copy SourceFiles="$(TargetDir)XIVComboExpanded.json" DestinationFolder="$(BaseOutputPath)" />
		<Copy SourceFiles="$(TargetDir)XIVComboExpanded.dll" DestinationFolder="$(BaseOutputPath)" />
		<Copy SourceFiles="$(TargetDir)XIVComboExpanded.deps.json" DestinationFolder="$(BaseOutputPath)" />
		<Copy SourceFiles="$(TargetDir)XIVComboExpanded.pdb" DestinationFolder="$(BaseOutputPath)" />
	</Target>
```
