### ISSUE TITLE
XL Log - An item with the same key has already been added. Key: MonkDemolishFeature

### ISSUE THREAD

**Issue by SubaruYashiro** [daemitus/XIVComboPlugin#155]
Version used: v1.3.2.28

![image](https://user-images.githubusercontent.com/96951106/156100670-d8309b27-53df-4a55-a608-634a9f96d2da.png)

**Comment by daemitus** [comment]
Can you check if you get it with a fresh config?

**Comment by daemitus** [comment]
I added a potential mitigation to this in .30
