### ISSUE TITLE
[DRK] Combo Chain displayed ability sometimes gets stuck

### ISSUE THREAD

**Issue by zbee** [daemitus/XIVComboPlugin#157]
I haven't been able to figure out what it is, but sometimes the combo chain for stalwart soul and for souleater will sometimes get stuck visually only, displaying the last ability in the chain at all times.
The correct ability is used in combo, so the chain still works, it just stops updating the visual for the ability - even the highlighting of a combo ability works when it gets to the last ability.

So nothing is broken functionality wise, just a visual bug it seems.

**Comment by daemitus** [comment]
check if you've got any other plugins messing with the display of the slot.
Simple tweaks has an option for compatibility for example.

**Comment by zbee** [comment]
I'm not completely certain which type of changes would affect this, but I do have a few that could I imagine.
SimpleTweaks, MaterialUI, ReAction (though only for the settings, no Stacks), and DelvUI.
However, I also had all of these before last night without this issue occurring, with similar or unchanged configuration.

As for the the SimpleTweaks compatibility, I looked through what I have active in there and didn't see anything like that. Where's that at?

So far, it only happened last night, but I'll see if I can reproduce the issue. I also see nothing in the logs about it, even from another plugin.

**Comment by Grammernatzi** [comment]
I mean, it is entirely possible the icon replacer in the game just bugged out. The client is a mess of spaghetti code, something is bound to fuck up at some point. Thankfully I didn't seem to actually affect the gameplay.

**Comment by daemitus** [comment]
No idea. but if you can reliably reproduce the issue let me know.
