### ISSUE TITLE
RPR overcap features

### ISSUE THREAD

**Issue by godfall22** [daemitus/XIVComboPlugin#158]
Hi, I am just wondering, is there any reason why the overcap features are greater than 50 soul gauge and not AT and greater than 50 soul gauge?
I seem to be running into the issue where If I wanted to use Bloodstalk or Grimswathe at 50 then I cannot and have to add an additional slice.

Thanks

**Comment by Grammernatzi** [comment]
They're designed to prevent overcap, not to replace buttons. There's no way to properly replace the button with this feature because there's times where you want to use Soul Slice at 50.
