### ISSUE TITLE
[AST] Request: Delay option on Crown Play to Minor Arcane or the reverse.

### ISSUE THREAD

**Issue by Kylis** [daemitus/XIVComboPlugin#160]
I have minor arcana on a key I have set to repeat in general for other jobs and such and sometimes end up using the drawn card on accident, can there be an option to delay the swap like there is for reapers regress?

**Comment by daemitus** [comment]
We could check the cooldown of minor arcana, what sort of delay is appropriate?

**Comment by Maya1924** [comment]
Kylis told me over Discord they forgot their login, however they told me a 1s delay should be fine!

**Comment by daemitus** [comment]
1s delay now implemented
