### ISSUE TITLE
ability icon replacement not working for some features on new launcher/dalamud version released 2022-03-31

### ISSUE THREAD

**Issue by rz-1** [daemitus/XIVComboPlugin#162]
For example on DNC I have the Fan Dance 3 Feature and Devilment Feature enabled. When I use Devilment the button is replaced with Starfall Dance, but the icon does not update.
![before moving ability](https://user-images.githubusercontent.com/73505906/161094243-dfa315d7-b649-44e1-a400-0e53a03ade53.png)
If I move the ability to a different hotbar location (and optionally back to the original location), the icon is correctly replaced with Starfall Dance.
![after moving ability](https://user-images.githubusercontent.com/73505906/161095446-57907083-2c33-4266-a16b-670cec16cf5b.png)

The icon is not being replaced for Fan Dance 3 and 4 Features same as above.

Conversely, with Single Target and AOE Multibutton enabled the Cascade and Windmill ability icons are correctly replaced by their combos and procs.

This issue started for me today after updating the xiv launcher/dalamud.

**Comment by daemitus** [comment]
Typically icon issues are either related to another plugin, or combo itself being updated. Does it happen with just combo installed?

**Comment by rz-1** [comment]
After a few more dalamud updates the issue went away on its own and the icon is being replaced now. I'll close the issue.

Weird, because I was able to reproduce by exiting the game and restarting it. To respond to your comment, I haven't added any new plugins recently and everything has been stable for awhile.
