### ISSUE TITLE
DNC: Single Target to Procs not working for Cascade

### ISSUE THREAD

**Issue by Seanana92** [daemitus/XIVComboPlugin#164]
The new Silken Symmetry buff gained when casting Cascade doesn't swap Cascade to it's proc. Flourish's procs swap in correctly, Oddly, the procs work fine when using Single Target Multibutton.

Single Target to Proc

https://user-images.githubusercontent.com/82492838/163575940-4134d304-5553-4164-9110-c23c64855207.mp4

Single Target Multibutton

https://user-images.githubusercontent.com/82492838/163576149-ecebd6e1-5e8c-4ac7-a9b1-a30fa87553a2.mp4

**Comment by Grammernatzi** [comment]
https://github.com/daemitus/XIVComboPlugin/blob/2f4c589bcc4d6cc9fca35775662c599566918741/XIVComboExpanded/Combos/DNC.cs#L235 is missing a check for Silken Symmetry.

**Comment by daemitus** [comment]
workin  it
