### ISSUE TITLE
[SGE] Bug: Phlegma into Toxikon/Dyskrasia bug when synced below level 66

### ISSUE THREAD

**Issue by nashutal** [daemitus/XIVComboPlugin#166]
Hi! Currently if you enable both Phlegma into Toxikon + Phlegma into Dyskrasia, Phlegma will still transform into Toxikon when you're synced below level 66 (the level when you get Toxicon/Addersting) if you have a target selected, despite not being able to use Toxikon. If you deselect your target, it will turn into Dyskrasia still.

This does not happen if you're 66 or above and it functions exactly as it did pre-patch if you're able to use Toxikon/Addersting charges. I made sure there were no other addons conflicting when I tested it at multiple different levels.

I have no concrete proof, but one potential cause of this issue might have something to do with the fact that SGE now starts dungeons with 3 stacks of Addersting. Except below 66 you can't use your Addersting charges or see that you have it. Wondering if the way they coded it makes it seem like you have Addersting charges to spend despite being too low to use them. So the addon might be seeing that you have 3 stacks of Addersting and thus concluding you should be able to use Toxikon? Except you're technically too low for it.

**Comment by Grammernatzi** [comment]
I wouldn't be surprised if that's the case. The same thing happened with Beast Gauge on Monk, as well. I guess sometimes redundant level checks aren't so redundant after all. In any case, it's a quick fix, there just needs to be a level check added for Toxikon.

**Comment by daemitus** [comment]
this should be fixed. @Grammernatzi what broke on mnk?

**Comment by Grammernatzi** [comment]
> this should be fixed. @Grammernatzi what broke on mnk?

Oh, it was a long time ago and it already got fixed, but basically you still accumulated beast chakra even before you could use it. So you actually needed a level check, otherwise it would mess with stuff. But this was already fixed a while ago, like I said.
