### ISSUE TITLE
[Melee suggestion] First combo skill turns into the ranged skill based on distance from target

### ISSUE THREAD

**Issue by Nillinn** [daemitus/XIVComboPlugin#168]
Example: Ninja's first skill of the regular 1-2-3 combo (Gust Slash) turns into Knife Throw when further than max melee range based on the current target

**Comment by kaedys** [comment]
Honestly not a bad suggestion.  Could be applied to tanks as well.  Since they don't break combos anymore, the only time this would _really_ cause issues is if you're _just_ outside melee range, where it'd be better to just inch back in.

**Comment by daemitus** [comment]
Honestly, I'll probably never do this.
