### ISSUE TITLE
[BLM] 'Fire 2 Feature' proccing too soon

### ISSUE THREAD

**Issue by proulus** [daemitus/XIVComboPlugin#169]
"#33: (High) Fire 2 becomes Flare in AstralFire with 1 or fewer Umbral Hearts." except it's becoming Flare any time Enhanced Flare is procced, so it's proccing flare at 2 umbral hearts.  I've turned off every other option and this seems to be one doing it.

**Comment by Grammernatzi** [comment]
It got changed but the description wasn't updated. Honestly there really should just be an option to choose at this point. There's been enough heated debates about it and all over a tiny potential DPS increase in AoE. I say just let people pick what they want.

**Comment by daemitus** [comment]
Ive updated the description (soon)
