### ISSUE TITLE
[Request] Monk Dragon Kick / Bootshine only in Opo-Opo

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#170]
Currently, the Dragon Kick / Bootshine feature doesn't consider form bonuses, it unconditionally uses Bootshine if Leaden Fist is active.  However, if not in Opo-Opo (and thus missing the guaranteed crit bonus on Bootshine), Dragon Kick is actually superior potency (320 vs. 310).  In particular, the rather degenerate but quite functional and reasonably competitive Dragon Kick rotation (wherein one spams Dragon Kick, only deviating every ~7th hit to use Twin Snakes and Demolish) alternates between Dragon Kick and Bootshine for the Opo-Opo after Demolish, but otherwise just spams Dragon Kick.  Currently, this doesn't work with the Dragon Kick / Bootshine feature, as the _unbonused_ use of Dragon Kick after an Opo-Opo Dragon Kick will instead use Bootshine and waste the Leaden Fist proc.

Could either the existing feature be changed or a sub-option (similar to Formless Snakes Option) be added so that Dragon Kick is used over Bootshine, even if Leaden Fist is up, when not in Opo-Opo?  I'm on the fence as to whether this should be a sub-option, tbh.  On the one hand, using Bootshine over Dragon Kick when not in Opo-Opo is objectively a straight potency loss, as well as wasting the Leaden Fist proc on what could otherwise be a guaranteed crit Bootshine (once you're in Opo-Opo), but I could see arguments for it being a sub-option nonetheless.

**Comment by daemitus** [comment]
So to be clear: dragonkick turns into bootshine
currently -> if leaden fist is up
expected -> if leaden fist is up and in opo
