### ISSUE TITLE
[Bug] Expiring Perfect Bloodletter / Expiring Perfect Rain of Death

### ISSUE THREAD

**Issue by BeetleLord** [daemitus/XIVComboPlugin#173]
These features for Bard do not seem to work as intended. I've tested them a number of times, and Bloodletter does not transform into Pitch Perfect when there are procs available and Wanderer's Minuet is about to expire.

**Comment by daemitus** [comment]
I'll take a look soonish

**Comment by daemitus** [comment]
1.3.3.10
