### ISSUE TITLE
[Enhancement] Sidewinder Feature

### ISSUE THREAD

**Issue by BeetleLord** [daemitus/XIVComboPlugin#174]
If we could have Empyreal Arrow prioritized over Sidewinder, it would make this feature usable while performing the Bard rotation optimally.

Empyreal Arrow is supposed to be used almost immediately during the opener, whereas Sidewinder should be reserved until all raid buffs are active. Therefore, when combined onto the same button, Empyreal Arrow should be prioritized.

Alternatively it could be an new feature called "Empyreal Arrow Feature", which transforms Sidewinder into Empyreal Arrow whenever Empyreal Arrow is available.

**Comment by daemitus** [comment]
This should be easy to fix, I just need to find some time to get around to
doing it.

**Comment by daemitus** [comment]
1.3.3.9
