### ISSUE TITLE
[BRD] Request: Shadow Barrage feature

### ISSUE THREAD

**Issue by BeetleLord** [daemitus/XIVComboPlugin#175]
This feature would replace Quick Nock, Ladonsbite and Shadowbite with Barrage under the following conditions:

"Shadowbite Ready" is applied
"Barrage" is ready to use

It would be compatible with the "Quick Nock into Shadowbite" feature by taking priority over Shadowbite.
Basically, it forces you to use Barrage (if it's available) before consuming a Shadowbite proc.

**Comment by daemitus** [comment]
Added under the existing quick/ladonsbite feature.
