### ISSUE TITLE
[MNK] Enhancement for RoF/RoW/Brotherhood

### ISSUE THREAD

**Issue by BeetleLord** [daemitus/XIVComboPlugin#177]
I enjoy the features "Riddle of Brotherly Fire" and "Riddle of Fire and Wind" since, when used in conjunction, it allows MNK buff management to be handled by a single hotkey. However, there is one serious issue with it, which is that you can't see how long until the next buff comes off cooldown. It defaults to displaying Riddle of Fire when the others are on cooldown. This makes it unnecessarily difficult to immediately react to the next buff being available, since you would essentially have to memorize when it's going to occur, or have extra hotkeys just to see the cooldowns. It also makes it impossible to use skill queueing to weave optimally since the button won't be available to press until it's already off cooldown.

I propose that both of these features be changed to display whichever skill is currently lower on its cooldown. And when both features are enabled, the button should display the lowest cooldown out of all three skills (RoF/RoW/Brotherhood).

**Comment by daemitus** [comment]
Whats the current recommended priority between all 3? Like in your
opener/in general.

**Comment by daemitus** [comment]
found it. fire > brotherhood> wind. 

updating shortly.
