### ISSUE TITLE
[DRG] Request: Geirskogul / Nastrond to Wyrmwind Thrust

### ISSUE THREAD

**Issue by BeetleLord** [daemitus/XIVComboPlugin#179]
As Wyrmwind Thrust is very similar to Geirskogul and Nastrond in its functionality, I would like to request an option to condense them all into the same button. I suppose Wyrmwind should take lower priority than the other 2 skills, since it isn't on a strict cooldown and has a several GCD window to be utilized before overcapping with another Firstmind's Focus.

**Comment by daemitus** [comment]
great idea. added.
