### ISSUE TITLE
[NIN] Huraijin / Armor Crush Combo enhancement

### ISSUE THREAD

**Issue by BeetleLord** [daemitus/XIVComboPlugin#180]
This feature is great, but there is one improvement I would like to suggest. Huraijin should only turn into Armor Crush if the Huton buff is present. It's pointless (potency loss) to use Armor Crush if Huton isn't active to be refreshed. Additionally, the fact that Armor Crush isn't showing up would serve as a nice reminder that you forgot to put up the Huton buff, allowing you to press Huraijin instead, which won't break the combo.

**Comment by daemitus** [comment]
ill probably get to this once im done fiddling with zodiac buddy

**Comment by daemitus** [comment]
done
