### ISSUE TITLE
REQUEST: Healer and SMN/RDM Raises replaced by Variant Raise II while in ASS.

### ISSUE THREAD

**Issue by Jacien** [daemitus/XIVComboPlugin#196]
Variant Raise II's ID is 29734

ASS is Another Sil'dihn Subterrane.

Would only work for "normal" ASS and not Savage ASS. As the Savage ASS doesn't let you raise at all.

**Comment by daemitus** [comment]
I'll need the zone ID

**Comment by kaedys** [comment]
Splatoon says the zone ID for the regular (solo) version is 1069, the regular group version is 1075, and the savage one is 1076.

**Comment by daemitus** [comment]
Should be available in the next release
