### ISSUE TITLE
Paladin Request: FoF / Requiescat feature

### ISSUE THREAD

**Issue by BeetleLord** [daemitus/XIVComboPlugin#199]
![image](https://user-images.githubusercontent.com/96172665/212697455-ce52fb00-5929-497f-a136-fa1c00c9d45e.png)

In the new standard Paladin rotation, FoF and Requeiscat will always be used together as a pair, during both the opener and burst phases. They also have the same cooldown.

Therefore I propose a feature that combines the two into a single button, similarly to the Scornful Spirits feature that combines Circle of Scorn with Spirits Within. If both are up, FoF should be prioritized over Requiescat to ensure that Requiescat's potency is buffed by FoF.

To me this makes more sense than combining FoF and Goring Blade, which places a GCD and an oGCD onto the same button. It also creates symmetry with the Scornful Spirits feature which combines two oGCDs together. The pattern during opener and burst would then be: double tap oGCDs, Goring Blade, double tap oGCDs.

FoF + Goring Blade also seems sub-optimal because double-tapping the button would always produce an incorrect weaving order. Examples:
Req -> FoF -> Goring misses buffed potency on Req.
FoF -> Req -> Goring requires an awkward series of button presses since you aren't double-tapping the FoF/Goring button.
FoF -> Goring -> Req pushes the Req into the next weaving window, which displaces other oGCDs or forces triple weaving.

However if some people are a fan of FoF + Goring they could both exist as mutually exclusive features.

This is my primary request, but while I'm at it, I will also mention that it would be nice if the "Royal Authority Divine Might Feature" could work without the prerequisite of enabling the "Royal Authority Combo" feature.

**Comment by Grammernatzi** [comment]
FoF + Goring works fine for me with the above rotation with no issues. However, I can definitely see this working fine, as well. FoF + Requiescat + Goring would likely work okay all in one. The actions get queued properly so you don't lose GCD uptime. Also, you don't HAVE to start with goring, it's just recommended. You don't lose damage if you, say, use one of your GCD fillers first and then use goring blade or confiteor.

**Comment by daemitus** [comment]
@BeetleLord 
I threw fof on req after the blade/conf/holy.

So the priority should be:
- blades active? blades
- conf ready buff? conf
- req buff? holy spirit
- fof off cd? fof

I think that about works.

I also moved divine might to the highest priority on royalAuthority. So it should go:
- divine might? holy spirit
- sword oath? atonement
- 1-2-3 combo

**Comment by daemitus** [comment]
https://github.com/daemitus/XIVComboPlugin/commit/9de0c08cad742c71ec3a4a885fad21314a28bb4f

**Comment by BeetleLord** [comment]
Works great now, thank you.
