### ISSUE TITLE
"Royal Authority Divine Might Feature" not working as intended

### ISSUE THREAD

**Issue by dekw** [daemitus/XIVComboPlugin#205]
Ever since the most recent update to the addon, the **Royal Authority Divine Might Feature** for the Paladin class now seems to also replace Atonement with Holy Spirit, effectively forcing you to use it immediately rather than before the next Royal Authority cast.

I also have the **Royal Authority Atonement** feature active (the screenshot is just of my paladin configuration).

![image](https://user-images.githubusercontent.com/741563/214069579-d1e63322-502d-4bd1-91dd-ad45b9fbde60.png)

**Comment by BeetleLord** [comment]
I was just about to come here and post this bug. Glad to see it's already been spotted.

**Comment by dekw** [comment]
Seems to be working as intended again. Thank you!
