### ISSUE TITLE
97/98 festering/painful ruin a little awkward in practice?

### ISSUE THREAD

**Issue by neongrey** [daemitus/XIVComboPlugin#21]
I'm not sure if this particular combo works-- ruin 4 is on the GCD and fester and painflare are both oGCD so it feels a little awkward to me. I think a possible alternative would honestly be for it to just replace ruin 1/2/3 when both not attuned and further ruin is active

**Comment by daemitus** [comment]
I agree. 

I'm thinking replace ruin1/2/3 and outburst/tri when either 1: attuned to any of ifrit,titan,garuda, or not attuned to baha/phoenix.

Since ruin doesn't change while attuned to the elemental primals, its safe to change. Only baha/phoenix change ruin. the rest use gemburst.

**Comment by neongrey** [comment]
Yeah, that sounds like a solid way of handling it. Thanks!

**Comment by daemitus** [comment]
please view the other smn issue and let me know your thoughts.
