### ISSUE TITLE
Update for 6.4

### ISSUE THREAD

**Issue by Dranni21312** [daemitus/XIVComboPlugin#224]
Version v1.4.0.15 throws an error while loading since the 6.4 update

> 2023-05-23 18:23:33.055 -05:00 [ERR] [LOCALPLUGIN] Error while loading XIV Combo Expanded
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Collections.Generic.KeyNotFoundException: Can't find a signature of F3 0F 11 05 ?? ?? ?? ?? F3 0F 10 45 ?? E8
>    at Dalamud.Game.SigScanner.Scan(IntPtr baseAddress, Int32 size, String signature) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 147
>    at Dalamud.Game.SigScanner.ScanText(String signature) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 330
>    at Dalamud.Game.SigScanner.GetStaticAddressFromSig(String signature, Int32 offset) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 184
>    at XIVComboExpandedPlugin.PluginAddressResolver.Setup64Bit(SigScanner scanner) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboExpanded\PluginConfiguration.cs:line 93
>    at Dalamud.Game.BaseAddressResolver.Setup(SigScanner scanner) in C:\goatsoft\companysecrets\dalamud\Game\BaseAddressResolver.cs:line 54
>    at XIVComboExpandedPlugin.XIVComboExpandedPlugin..ctor(DalamudPluginInterface pluginInterface) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboExpanded\Combos\AST.cs:line 112
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    --- End of inner exception stack trace ---
>    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 119
>    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 444
>    at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 886
> 2023-05-23 18:23:33.065 -05:00 [INF] [PLUGINM] Regular plugin failed to load, adding anyways: XIVComboExpanded.dll
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Collections.Generic.KeyNotFoundException: Can't find a signature of F3 0F 11 05 ?? ?? ?? ?? F3 0F 10 45 ?? E8
>    at Dalamud.Game.SigScanner.Scan(IntPtr baseAddress, Int32 size, String signature) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 147
>    at Dalamud.Game.SigScanner.ScanText(String signature) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 330
>    at Dalamud.Game.SigScanner.GetStaticAddressFromSig(String signature, Int32 offset) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 184
>    at XIVComboExpandedPlugin.PluginAddressResolver.Setup64Bit(SigScanner scanner) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboExpanded\PluginConfiguration.cs:line 93
>    at Dalamud.Game.BaseAddressResolver.Setup(SigScanner scanner) in C:\goatsoft\companysecrets\dalamud\Game\BaseAddressResolver.cs:line 54
>    at XIVComboExpandedPlugin.XIVComboExpandedPlugin..ctor(DalamudPluginInterface pluginInterface) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboExpanded\Combos\AST.cs:line 112
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    --- End of inner exception stack trace ---
>    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 119
>    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 444
>    at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 886

**Comment by daemitus** [comment]
Fix incoming
