### ISSUE TITLE
RDM issues in 6.4

### ISSUE THREAD

**Issue by Dranni21312** [daemitus/XIVComboPlugin#225]
I noticed a couple of issues when using the plugin on RDM in 6.4:

- Contre Sixte / Fleche feature is not working
- Embolden to Manafication feature is not working (Manafication is also misspelled as Mana**i**fication)
- Acceleration with Swiftcast works, however, the icon is visually not replaced (with swiftcast off CD, acceleration does not show as swiftcast, but pressing it does trigger swiftcast)

Thank you for maintaining the plugin!

**Comment by Grammernatzi** [comment]
Have you already tried doing things like switching jobs, moving the actions on your hotbar and reinstalling the plug-in from scratch?

**Comment by Dranni21312** [comment]
That got fixed after entering the dungeon, leaving, and re-entering. Can be closed. Thanks!
