### ISSUE TITLE
Play into Astrodyne

### ISSUE THREAD

**Issue by 542673** [daemitus/XIVComboPlugin#28]
Making Astrodyne replace play when we already have 3 seals, would be great to make it work with the current draw into play option (so we can still draw while having 3 seals and then swap play into astrodyne if 3 seals)

**Comment by Grammernatzi** [comment]
`var gauge = GetJobGauge<ASTGauge>();
if (!gauge.ContainsSeal(SealType.NONE))
                    return AST.Astrodyne;`

Code for said feature if Daemitus wants to add it.

**Comment by daemitus** [comment]
available in .22
