### ISSUE TITLE
Atonement Feature

### ISSUE THREAD

**Issue by Alkeyd** [daemitus/XIVComboPlugin#30]
The Atonement Feature only works when the Royal Authority Combo is on, is there a way to separate the two? For Feature to change Royal Authority without turning on the combo option, if you have a way to put the Goring Blade to transform into Atonement it would also be very good.

**Comment by daemitus** [comment]
`1.3.0.14`
Atonement split from Royal Authority, also added to Goring Blade

**Comment by Alkeyd** [comment]
Thank you!
