### ISSUE TITLE
SAM Iaijutsu and Tsubame-Gaeshi broken

### ISSUE THREAD

**Issue by dvdio** [daemitus/XIVComboPlugin#32]
Any combo that uses Iaijutsu or Tsubame-Gaeshi doesn't seems to work with the 1.3.0.15 update, with the previous patch it was fine.
(thank you for your work, it hallows me to play the game even with my conditions!)

**Comment by daemitus** [comment]
problem identified, stay tuned for a new version shortly.

**Comment by daemitus** [comment]
reopen if the issue persists  please

**Comment by dvdio** [comment]
The Iaijutsu and Tsubame-Gaeshi are broken again with the new patch.
Didn't check the Shinten to Shoha and the other new feature in time (got dc sadly).
After que of 3.5k finish i will give you an update on those.

**Comment by daemitus** [comment]
```
            if (actionID == SAM.TsubameGaeshi)
            {
                var gauge = GetJobGauge<SAMGauge>();

                if (IsEnabled(CustomComboPreset.SamuraiTsubameGaeshiShohaFeature))
                {
                    if (level >= SAM.Levels.Shoha && gauge.MeditationStacks >= 3)
                        return SAM.Shoha;
                }

                if (IsEnabled(CustomComboPreset.SamuraiTsubameGaeshiIaijutsuFeature))
                {
                    if (level >= SAM.Levels.TsubameGaeshi && gauge.Sen == Sen.NONE)
                        return OriginalHook(SAM.TsubameGaeshi);

                    return OriginalHook(SAM.Iaijutsu);
                }
            }
```

**Comment by daemitus** [comment]
OriginalHook just returns whatever the game decides should be sent. 

does the combo not replace anything at all, get stuck somewhere?
