### ISSUE TITLE
[Suggestion] Reaper additions

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#33]
In addition to the existing options, I'd like to suggest the following:

* Gibbet and Gallow (and anything that has been replaced to them, like Infernal Slice and Shadow of Death, if those options are set) are replaced by Lemure's Slice when you have >=2 Void Shroud charges.
* Guillotine (et al) is replaced by Lemure's Scythe when you have >=2 Void Shroud charges.
* Gibbet, Gallows, and Guillotine are replaced by Communio when you have 1 Shroud charge left and 0 Void Shroud charges.
* As an alternative option to the above (for those that don't want to merge Communio into the others), Communio is replaced with Void Reaping (or Cross Reaping, depending on which is enhanced atm) or Grim Reaping (if it was the last Shroud spender you used) when under or synced to under level 90, so you don't have to mentally remap your key usage during Enshroud when synced.

Personally, I'd only use the first 3.  I have Enshroud on a key that I tend to put oGCDs on, so having Communio on it is awkward, but I don't like having Communio separately on the bar either, both because of the syncing issue referenced in the fourth bullet (having to remember to use another Reaping ability instead for that 5th charge, and then having to remember to go back to using Communio after not synced anymore) and because it's just annoying to have it there for a single usage per Enshroud.  The first two bullets are for similar purpose to the Continuation option, as well as the inclusion of Shoha in the Ogi combo option, removing the need to hit a second button for the weave that's supposed to occur.

If that's too far, though, the 3rd bullet alone would solve a decent amount of my frustration with the Enshroud combo.

**Comment by Grammernatzi** [comment]
The only issue is that the Reaper gauge functions in Dalamud aren't finished. I recall Daemitus talking about adding stuff like this once it was. I already have the code set up for the third option, myself, but haven't been able to put it in as a result.

**Comment by kaedys** [comment]
👍 When writing it, part of me was wondering if they'd gotten that done yet.  Glad to see it's on the radar, though.  Thoughts on the first two bullets?

**Comment by Grammernatzi** [comment]
First two bullets should be fine, with the same logic as Continuation or the Mountain Buster feature (which isn't in this fork yet, but still). As for seeing if something is 'usable', we haven't found the specific flag that the game uses to figure that out. Gauge would likely be easier for the time being.

**Comment by Grammernatzi** [comment]
Also, it appears I might've been wrong about the gauge, it looks like it's been updated now. I'll work on the code for these features, and Daemitus can add them later.

**Comment by kaedys** [comment]
👍

**Comment by daemitus** [comment]
Yup, I got the gauge stuff in thanks  to some grindy folks helping define what was added.

**Comment by daemitus** [comment]
1.3.0.29 should be released soon with some reaper stuff. Can't test it so let me know whats broken.

**Comment by kaedys** [comment]
https://github.com/daemitus/XIVComboPlugin/blob/master/XIVComboExpanded/CustomComboPreset.cs#L418

Looks like this line's ID trampled the ID for the Regress option, seen here:

https://github.com/daemitus/XIVComboPlugin/blob/master/XIVComboExpanded/CustomComboPreset.cs#L431

Result is that there's no entry in the mod menu for the Lemure's Slice feature, and the Regress feature is listed twice (as both 88 and 89).  The line for 89 is not clickable, but when 88 is clicked, it checks both lines.  This _does_ result in the Lemure's Slice feature working in the mean time, however.

**Comment by daemitus** [comment]
should be fixed in .30

**Comment by daemitus** [comment]
last of the suggestions will be available soon.
