### ISSUE TITLE
[MNK] Combo bug and suggestions

### ISSUE THREAD

**Issue by ParasiteXX** [daemitus/XIVComboPlugin#36]
The AOE combo and Howling Fist/meditation feature isn't working for me. It's possible it's not working because I'm only lv65.

In addition I would suggest a combo feature. Dragon Kick => Bootshine.
When Leaden Fist and the correct form or formless/perfect balance is active, then change Dragon Kick into Bootshine.
Dragon Kick on it's own will do more damage than a Bootshine that either has only Leaden Fist but not form. And vice versa with the guaranteed crit but no Leaden Fist.
Also have Dragon Kick change into Bootshine when level synced below lv50.
Will save 1 button

Another suggestion that would fit more in with the secret forbidden knowledge category. 
Would be to have True Strike turn into Twin Snakes when the damage buff Disciplined Fist isn't up or are a few seconds from running out and need to be refreshed. This will also save 1 button.

**Comment by daemitus** [comment]
view `/xllog` is there alot of red? Are you on dalamud testing?

**Comment by ParasiteXX** [comment]
Ah yeah. there is a lot of red related to MonkAOEcombo. And I'm pretty sure I'm not on a Dalamud testing build.

15:58:12.673 | ERR [XIVComboExpanded] Don't crash the game
System.MissingMethodException: Method not found: 'Dalamud.Game.ClientState.JobGauge.Enums.BeastChakra[] Dalamud.Game.ClientState.JobGauge.Types.MNKGauge.get_BeastChakra()'.
   at XIVComboExpandedPlugin.Combos.MonkAoECombo.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level)
   at XIVComboExpandedPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, UInt32 lastComboActionID, Single comboTime, Byte level, UInt32& newActionID) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboExpanded\CustomCombo.cs:line 90
   at XIVComboExpandedPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboExpanded\IconReplacer.cs:line 76

**Comment by daemitus** [comment]
I've re-implemented the monk gauge changes in combo itself, this should be a good bandaid until dalamud is updated. Please let me know how it works.

**Comment by daemitus** [comment]
`1.3.0.23`
