### ISSUE TITLE
[SMN] Oversight? Gemshine -> Enkindle Bahamut

### ISSUE THREAD

**Issue by Zynyx** [daemitus/XIVComboPlugin#37]
I see the Enkindle function swaps Gemshine -> Enkindle Bahamut when not attuned to anything. I could see why you might want this for Astral Flow (which would attune then to Bahamut/Phoenix when you dont have a summon out and be useful), but I can't imagine a use case where Gemshine swapping to Enkindle Bahamut is useful to anyone.

**Comment by daemitus** [comment]
ill be working more on this tonight, some initial guesses were made that
turned out to be false

**Comment by daemitus** [comment]
Ok, added astral > enkindle, in addition to the gemshine > enkindle. Options are good. Open up another issue (or reopen this) if you have more feedback. Thank you :)

**Comment by Zynyx** [comment]
Meep - I gave you the wrong ability for this -- This should have been Summon Phoenix -> Enkindle Bahamut/Phoenix -- Not astral flow. 

Doing it with Astral Flow breaks Bahamut by not letting you death flare and also breaks when you use Titan as it swaps to Enkindle Bahamut on the last Mountain buster instead of letting you finish your combo.

Flow should be Summon Bahamut  -> Enkindle Bahamut -> Summon Phoenix -> Enkindle Phoenix
