### ISSUE TITLE
Summoner Shiny Outburst Feature Bug

### ISSUE THREAD

**Issue by Azshadris** [daemitus/XIVComboPlugin#38]
Outburst(tri-disaster) is not changed to Precious Brilliance. Gemstone feature works flawlessly.

**Comment by Azshadris** [comment]
![image](https://user-images.githubusercontent.com/96094906/145920018-1f70820a-bb56-44c4-ac67-a00e988e52f0.png)
![image](https://user-images.githubusercontent.com/96094906/145920045-ebba8cc6-e520-4d7b-b800-d96314e1556f.png)

**Comment by Azshadris** [comment]
As you can see I have Ifrit active. And Tri-Disaster doesn't turn to Brilliance. But Ruin turns(it is on 1 key) into Gemstone ok.

**Comment by Grammernatzi** [comment]
Strange, I can't find a reason why this would be broken. Your plugin is fully updated, yes? Also, see if dragging outburst to your bar works.

**Comment by Azshadris** [comment]
![image](https://user-images.githubusercontent.com/96094906/146003036-75693a3b-deb0-4271-9ba6-7f04eabd569e.png)
Tried Outburst, ofc it turns to Tri-disaster and still doesn't work

![image](https://user-images.githubusercontent.com/96094906/146003148-188ff809-9a7d-4930-b6c2-37f80b777d66.png)
Is this latest?

**Comment by Grammernatzi** [comment]
Oh, you're using a different fork. That's why. Try using this one, using the repo in the readme.

**Comment by daemitus** [comment]
Ok. new stuff coming down the pipe, please check which combos you have enabled and let me know if anything doesn't work. 

Thanks :D

**Comment by daemitus** [comment]
`1.3.0.23`
