### ISSUE TITLE
Warrior's Primal Rend feature is not very well thought out

### ISSUE THREAD

**Issue by SashaFFXIV** [daemitus/XIVComboPlugin#39]
Replacing Fell Cleave with Primal Rend is just about the worst possible option you could have used. Not only are there many situations where you would not want to use Primal Rend immediately after IR (like holding it slightly for mobility or healing BW/NF), there are also situations where you _literally cannot use Primal Rend._ If you are bound by any means (Like, you know, one of the Extreme trials does right now) you are unable to use gapclosers, which means you cannot use Primal Rend and are now incapable of utilizing Inner Release at all. You either have to hold your GCD or burn Inner Release stacks on your 1-2-3 combo.

If you want to keep it for whatever reason, fine. But please add the option that the main plugin has that replaces _Inner Release_ with Primal Rend instead. It's an infinitely better option.

**Comment by daemitus** [comment]
this will be addressed soon, thanks for the feedback.
