### ISSUE TITLE
SAM Iaijutsu and Tsubame-Gaeshi broken (patch 1.3.0.20+)

### ISSUE THREAD

**Issue by dvdio** [daemitus/XIVComboPlugin#40]
The Iaijutsu and Tsubame-Gaeshi are broken again with the new patch.
Didn't check the Shinten to Shoha and the other new feature in time (got dc sadly).
After que of 3.5k finish i will give you an update on those.

**Comment by daemitus** [comment]
Ill check it myself tonight too, gotta head off to work

**Comment by daemitus** [comment]
got a report that it might just be fixed, please let me know if the latest version solves your issue :)

**Comment by dvdio** [comment]
Yes, perfectly!!
