### ISSUE TITLE
[MNK] AoE changes

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#41]
RE: #26 

The latest changes appear to be a big odd.  Rockbreaker properly runs through the AoE combo, but Four-point Fury does not appear to.  FPF is always FPF, regardless of form, and during Perfect Balance, just sticks on Arm of the Destroyer (my monk is at 73, and thus lacks Shadow of the Destroyer).  It's also a bit counter-intuitive, even if it was working as I had inferred from the description, since the button that normally cycles through the forms (Rockbreaker) becomes the one that uses the same ability 3 times during PB.

How I think it would make more sense to work:

* Rockbreaker uses all 3 abilities, in sequence, during PB, depending on which chakra you don't yet have (with the goal of getting all 3 different chakra)
* Rockbreaker prioritizes Four-point Fury if the buff is not active (or < a certain duration? /shrug) during Formless Fist (and during PB, if you also lack that chakra), else it restarts the cycle with Arm/Shadow.
* Rockbreaker cycles through the forms normally when not in PB.
* Arm/Shadow always uses Shadow if >= 82, else Rockbreaker (because higher potency).

Basic idea is that Rockbreaker is your "normal" DPS button.  It cycles through the forms, and has that same behavior in AoE, cycling through the 3 forms for the 3-chakra finishers.  Arm/Shadow is the alternative for the 3-same finisher you need for the Elixir Field for the Lunar Nadi.  It's basically unmodified, except that it swaps to Rockbreaker when under 82 for the higher potency (mostly there for syncing down below 82).  This way the behavior of the buttons doesn't change substantially during PB.  The one that cycles through the forms (Rockbreaker) cycles through the forms both in and out of PB, and the one that doesn't (Arm/Shadow) doesn't even in PB.  This is also generally more useful, as your "normal" AoE button is the one you'll be spamming outside of PB, and 2 out of 3 PBs also need to use this sequence (3 different beast chakra) to get to Tornado Kick/Phantom Rush properly.  So you're only using the 3x Shadow sequence once every 2 minutes (in hypothetical sustained AoE) for the Lunar Nadi.

**Comment by daemitus** [comment]
I'll take another stab at this tonight

**Comment by daemitus** [comment]
Apparently I fucked the gauge in Dalamud and transposed the opo-opo and raptor beast chakra values. thats why it wasn't working.

As of right now, the combo actually rotates as expected. Now we can figure out how to next fix it.

**Comment by daemitus** [comment]
@kaedys  so the major difference between the current implementation and your recommendation, is rock should do the perfect balance 3 different beast chakra hunting, while FPF should lock during it to shadow/rock. basically flipping the PB condition between the two buttons?

**Comment by ParasiteXX** [comment]
I do like the way you set it up now, only with FPF starting the distinct PB combo instead of AOTD/SOTD. It already saves more than enough buttons on the AOE side when I play on controller. It's mainly just the single target combos that could use some combo features at this point. 
Dragon Kick into Bootshine would be a big improvement on that front. And maybe one that switches between True Strike or Twin Snake depending on Disciplined Fist status and time left on buff.

**Comment by kaedys** [comment]
> so the major difference between the current implementation and your recommendation, is rock should do the perfect balance 3 different beast chakra hunting, while FPF should lock during it to shadow/rock. basically flipping the PB condition between the two buttons?

In essence, yes, though I shifted the one that doesn't change to Arm/Shadow, since that's the one that, at 90, is cast repeatedly in PB for Elixir Field.  Right now, from what I've been able to infer from the description, outside PB, Rockbiter cycles and FPF does not.  Inside PB, the opposite is true, Rockbiter casts a single ability repeatedly, and FPF cycles.  This is, imo, counter-intuitive.  Beyond that, Rockbiter is what is normally spammed during AoE, cycling through the forms, but the Elixir Field combo (3 of the same ability) is only used for 1 out of 3 PBs, while the 1-of-each is used for the other 2.  I feel like it would make more sense for Rockbiter to just always have the cycling logic, and Arm/Shadow just always not have the cycling logic (but have a _bit_ of logic there just for downranking during synced content, since below 82, Rockbiter is better than Arm or FPF).

**Comment by daemitus** [comment]
mmmm. I may have overly complicated things, but who cares.

OK. I haven't pushed this yet, looking for feedback first.
There are now several options, depending on how brainless you want to be.

In order of priority on Rockbreaker:
1. MonkAoEBalanceFeature (blitz when beast is full)
2. MonkAoELunarFeature (if PB is active, shadow/rock when lunar missing)
3. MonkAoESolarFeature  (if PB is active, acquire beast chakra when solar missing, FPF prioritized if fist is missing/expiring)
4. MonkAoEDisciplinedFeature (if formless is active, FPF if fist is missing/expiring)
5. MonkAoECombo  (regular form based combo)

For FPF:
1. MonkAoEFpfFeature (equivalent of the lunar feature, but on FPF)

Should MonkAoEDisciplinedFeature always do FPF to re-up fist? Should it default to shadow/rock if fist has a certain duration?

**Comment by daemitus** [comment]
also, should solar be prioritized over lunar to get fist active?

**Comment by ParasiteXX** [comment]
Solar does more damage with Rising Phoenix. So personally I would generally prefer to open that one first.
But i do also prefer having the choice between the 2 depending on situation. A 1 button does all is neat.. but a little excessive imo.
But it can be a neat feature to use when you just wanna no-brain through things. And keeping the option of the current 2 button choice for those who prefer to adapt.

**Comment by kaedys** [comment]
> Should MonkAoEDisciplinedFeature always do FPF to re-up fist? Should it default to shadow/rock if fist has a certain duration?

_I_ personally always restart my AoE combo after PB with FPF, just simply to guarantee I re-up the buff.  I don't think you _need_ to, necessarily, since a BP combo is only 4 GCDs, and you normally have 6 GCDs between applications of Disciplined Feature.  So starting with Shadow -> FPF refreshes the debuff exactly as normal in a single target sequence, on the 6th GCD, but that's only if you started PB immediately after FPF.  I just do it with Formless Fist after the finisher so I don't have to have concern for the timing.

Also, as above, recommend prioritizing Solar over Lunar, since it's 100 more potency (once you get Rising Phoenix, at least).

Oh, and your list doesn't mention it, but I presume that PB when you have both Nadi would work the same as Solar, using the 3 forms and then Phantom Rush.

**Comment by daemitus** [comment]
1.3.0.29 should be released soon with some monk stuff. let me know whats broken.

**Comment by daemitus** [comment]
if theres any more comments/issues regarding monk aoe, re-open this or just comment and I can address them. I think it's in a pretty good place right now.

**Comment by kaedys** [comment]
Yep, I've been playing around with it a bit today, and it seems to be working exactly as I'd expect it to.  Much appreciate the work and iteration on it!
