### ISSUE TITLE
[MNK] Four-point Fury bug

### ISSUE THREAD

**Issue by ParasiteXX** [daemitus/XIVComboPlugin#42]
When activating Perfect Balance, Four-point Fury changes to Arm of the Destroyer and gets stuck at that for the duration of Perfect Balance. And doesn't change even if you press the button.
And this happens even when none of the Monk features are selected.

**Comment by daemitus** [comment]
I'll take a look tonight

**Comment by ParasiteXX** [comment]
Bug seems to be fixed in latest build. Though now all the features stopped wroking again. I'm guessing it needs a test build of Dalamud to work correctly?

**Comment by daemitus** [comment]
do /xllog. lots of errors?

**Comment by ParasiteXX** [comment]
Yeah, constant non-stop stream of errors. Even with the monk features turned off.

00:13:47.052 | ERR [XIVComboExpanded] Don't crash the game
System.MissingMethodException: Method not found: 'Dalamud.Game.ClientState.JobGauge.Enums.BeastChakra[] Dalamud.Game.ClientState.JobGauge.Types.MNKGauge.get_BeastChakra()'.
   at XIVComboExpandedPlugin.Combos.MonkAoECombo.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level)
   at XIVComboExpandedPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, UInt32 lastComboActionID, Single comboTime, Byte level, UInt32& newActionID) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboExpanded\CustomCombo.cs:line 97
   at XIVComboExpandedPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboExpanded\IconReplacer.cs:line 76

**Comment by daemitus** [comment]
when was the last time you restarted the game

**Comment by daemitus** [comment]
Dalamud updated yesterday night and pulled in my latest gauge update. I can re-add it for now. I'll get to it in a few hours, gotta run outside.

**Comment by ParasiteXX** [comment]
Oh about 12 hours or so :P Been avoiding ques by remotely controlling my computer when I had to go away for more than 30min.

Ques should be low enough at this hour so ill give it a restart.

**Comment by ParasiteXX** [comment]
Error spam has stopped now. But only the Howling Fist feature seems to be working.

**Comment by daemitus** [comment]
put the entire gauge back in like it was yesterday, let me know how 1.3.0.28 works. Works for me 🤷

**Comment by ParasiteXX** [comment]
Did some quick testing before going to bed and everything seems to work perfectly now. 👍 
Only suggestion is maybe have Four-point Fury start as Four-point Fury instead of Arm/Shadow of Destroyer when doing perfect balance combo. As I would prefer opening with that to activate or refresh the Disciplined Fist damage buff. And it doesn't matter what order you do them in, as long as each beast chakra charge is distinctly different.

**Comment by daemitus** [comment]
fpf is now top of the list (pending the next push tomorrow?). depending on the other monk issue, which action locks and which rotates during PB may switch. I'll keep my gauge implementation in place until dalamud is fully updated.
