### ISSUE TITLE
[Suggestion] Summoner additions

### ISSUE THREAD

**Issue by Alkeyd** [daemitus/XIVComboPlugin#44]
I would be able to put the Shiny Titan's Favor feature also in Ruin III and Outburst, I use the feature so that Ruin III and Outburst become the summoned primal's spells, so they don't become Titan's OGCD even with Shiny Titan's Favor feature active

**Comment by Alkeyd** [comment]
Or at least make Titan's OGCD Feature work along with Ruin III's Feature and Outburst become the primal spell in use.

**Comment by daemitus** [comment]
it shall be done (soon)

**Comment by Alkeyd** [comment]
Thank you soo much!
