### ISSUE TITLE
[Suggestion] SAM features

### ISSUE THREAD

**Issue by Gotxiko** [daemitus/XIVComboPlugin#45]
Hello! Thanks for the work on this plugin :D 

I've got a suggestion for SAM that at least I would like to have.

Add the following:

- Replace Shifu with Kasha after using Shifu.
- Replace Jinpu with Gekko after using Jinpu.

This way one can have _Hakaze->Yukikaze_ combo on one button,  and then _Shifu->Kasha_ and _Jinpu->Gekko_ on another. This solves the "issue" of having three buttons with the same icon on the hotbar.

Would like to know if this is possible :)
Thank you!

**Comment by Grammernatzi** [comment]
This seems mostly cosmetic, but, fair. It does look rather weird as it is at the moment.

**Comment by Gotxiko** [comment]
Yeah, mostly cosmetic, nothing critical or urgent at all :)

**Comment by daemitus** [comment]
implemented in .31.
