### ISSUE TITLE
[WAR] Suggestions

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#48]
* Option to replace Inner Release with Primal Rend (like Enshroud -> Communio, Devilment -> Starfall Dance, Bunshin -> Kamaitachi, etc)
* Option to replace Fel Cleave and Decimate with Infuriate when <50 beast gauge (like Aetherflow -> Energy Drain, Energy Drain -> Fester, etc)

**Comment by Grammernatzi** [comment]
Isn't the first one already in?

Also, I experimented with the second one, main issue is that there's many times where you want to infuriate at 50 gauge. I guess as a helper it sort of works, but as a button replacement it doesn't.

**Comment by kaedys** [comment]
For the first one, you're right, it does exist.  Y'all either slipped it in on my without my noticing, or I at some point failed to scroll down all the way to see it.  The only one I'd seen was Primal Rend replacing Fel Cleave/Decimate, which I didn't want to use because there are situations where you want to hold on to that Primal Rend and not use it instant, especially since the buff permitting Primal Rend lasts a clean 30s, versus only 15s for the charges for Fel Cleave/Decimate.

The second one is not meant to _replace_ Infuriate on your bar, just to make it so if you hit Fel Cleave (or Decimate) for some reason and you lack the beast gauge for it, you'll end up casting Infuriate to generate that rage instead.  I guess that does differentiate it from the Scholar and Summoner versions, but Gunbreaker also has a nearly identical feature, where using a cartridge ability when your cartridge gauge is empty automatically uses Bloodfest instead.  I see basically zero difference, mechanically, between that and the Infuriate/spender feature in the second bullet.  Actually, probably even more reason for it to exist, because unlike Bloodfest, Infuriate has charges, so you can easily bank one for when you're short on beast gauge, whereas on Gunbreaker, you basically want to use Bloodfest on CD rather than simply when you're empty.

Unrelated, there was another issue out here talking about it that the OP of that issue ended up closing.  But the Nascent Flash -> Raw Intuition feature probably does not need to exist anymore, due to the changes in EW.  Raw Intuition now has the same healing on it that Nascent Flash does and also grants you DR, so there's never a reason to cast Nascent Flash for your own survivability over Raw Intuition/Bloodwhetting.  So replacing Nascent Flash, which is now exclusively a party-support ability (unlike pre-EW, when it was also used as a superior personal defensive vs Raw Intuition due to the healing), with Raw Intuition in synced content feels wrong.  It'd be like replacing Cover with Sheltron in synced content on a Paladin.  One is intended specifically for supporting/defending a party member, while the "replacement" is just a personal defensive.

**Comment by Grammernatzi** [comment]
> But the Nascent Flash -> Raw Intuition feature probably does not need to exist anymore, due to the changes in EW.

Honestly, Dae and I talked about this, but we figured that if we *did* remove it, someone would complain. So, we figured it was harmless enough to leave it for now, since it doesn't really hurt anything. I know I got rid of the Delirium feature because it was redundant now, on my fork, and someone complained about that, so, yeah.

**Comment by kaedys** [comment]
Ah, yes, [Hyrum's Law](https://www.hyrumslaw.com/).  Still, makes sense, doesn't really harm any other users, so might as well leave it in.

**Comment by daemitus** [comment]
Added infuriate when < 50 gauge. need to test reapy things, should be available soonish.
