### ISSUE TITLE
Combos that rely on ComboTime no longer function

### ISSUE THREAD

**Issue by remikan** [daemitus/XIVComboPlugin#5]
Please disregard, the problem was with pre-advancement jobs

**Comment by PrincessRTFM** [comment]
For those curious, the code checks your class/job ID before attempting to replace things. Jobs have different IDs than their base classes, so until you make it to 30, the plugin as is won't work. The fix isn't hard if you're willing to fork, edit, and compile your own, at least. It took me about five minutes to do, though I already had an existing modified fork.

In `CustomCombo.cs`, add this getter to the `CustomCombo` class:

```cs
public byte ClassID => this.JobID switch {
	19 or 20 or 21 or 22 or 23 or 24 or 25 => (byte)(this.JobID - 18),
	27 or 28 => 26,
	30 => 29,
	_ => this.JobID,
};
```

Then in the `TryInvoke()` method, change the check for

```cs
if (this.JobID != LocalPlayer.ClassJob.Id || !this.ActionIDs.Contains(actionID))
	return false;
```

to instead read

```cs
if ((this.JobID != LocalPlayer.ClassJob.Id && this.ClassID != LocalPlayer.ClassJob.Id) || !this.ActionIDs.Contains(actionID))
	return false;
```
