### ISSUE TITLE
[MNK] AoE ability selection bug

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#51]
**Selected Features:**
* Monk AoE feature
* Monk Disciplined AoE feature
* Monk Lunar AoE feature
* Monk Solar AoE feature
* Monk Four Point Fury AoE feature

**Issue:**
Using the AoE combo button sometimes casts Rockbreaker twice when missing the Solar Nadi, resulting in Celestial Revolution (the lowest potency of the Masterful Blitz options) being cast instead of Elixir Field or Flint Strike/Rising Phoenix.  It is difficult to isolate a reliable reproduction, as it is intermittent.  However, in every case I've seen of this, I've used it immediately after Four-point Fury (so the buff is active and high on duration), and it casts Arm of the Destroyer, then Rockbreaker twice.  However, on the third cast, the _icon_ on the bar is for Four-point Fury, it just actually _casts_ Rockbreaker.  This appears to happen mostly when I have no Nadi in the gauge at all, but occasionally occurs when I have both Nadi as well.  My monk is currently level 74, and thus lacks Shadow of the Destroyer.

**Debugging:**
I believe this may be a race condition related to when the buff for Perfect Balance falls off.  The last stack of Perfect Balance appears to fall off the instant you use the third ability.  If for some reason it fell off before this plugin's logic triggers, [this line](https://github.com/daemitus/XIVComboPlugin/blob/master/XIVComboExpanded/Combos/MNK.cs#L86) would fail to trigger, which would then fall back to [this line](https://github.com/daemitus/XIVComboPlugin/blob/master/XIVComboExpanded/Combos/MNK.cs#L158), returning the original action (Rockbreaker).

If my inference is correct, I'm not sure what the easy solution would be.  Can you detect when the gauge itself is active (ex. if PB isn't active, but the gauge has >0 Beast Chakra anyway, in this case 2/3)?  Another option would be to prioritize Four-point Fury over Rockbreaker during the Solar feature, but that could still result in incorrect results during the Lunar Nadi block when >74, since it could use 2 Shadow and then 1 Rockbreaker, so I think finding a solution to the race condition (if my inference is correct) is probably the best option.

I'm going to continue testing on this to see if I can isolate a more specific cause, but if it's the above race condition, reliable reproduction would be impossible.

**Comment by kaedys** [comment]
Seems almost definitely to be a race condition.  Sequence I used was enter combat -> AoE button twice (to put up the buff) -> Perfect Balance -> AoE button 3x.  Sometimes it does Four-point Fury on the 3rd PB attack, sometimes it does Rockbreaker (but always shows Four-point Fury as the icon before pressing the 3rd PB AoE).

Tangentially related, I think you can fall back to the logic for Lunar Nadi if you have both Nadi.  I _thought_ that Tornado Kick/Phantom Rush required 3 _different_ Beast Chakra when I recommended the changes to the AoE rotation, but through testing, found out that I'd misread the tooltip, and that all it requires is 3 Beast Chakra period with no specification on same or different.  Which means that spamming Shadow 3x (or Rockbreaker <74) when you have both Nadi is a small potency gain (versus using one from each form), and still lets you use Tornado Kick/Phantom Rush.

**Comment by Grammernatzi** [comment]
The solution I had to do was put the aoe combo on Masterful Blitz. That might be what he has to do as well.

**Comment by daemitus** [comment]
@kaedys For reference, this happens when you queue an action. 

I need to carve out some time to fix this properly sometime soon, however I need to give YesAlready some love in the meantime.

**Comment by daemitus** [comment]
I've migrated this to use masterful blitz like  grammer's variant. New monk options to put blitz on dragonkick should mitigate locking up the button for  aoe stuff.
