### ISSUE TITLE
DRK Suggestions

### ISSUE THREAD

**Issue by tommy8492nd** [daemitus/XIVComboPlugin#53]
DRK has alot of 60s cooldown abilities, namely 3.

I figured it'd be nice to save space on my controller if 1 button could hold both Blood Weapon and Abyssal Drain/C&S, while Delirium can stay in its own dedicated button. I figured since you'd probably use either ability only AFTER TBN or Attack of Shadow, it can be hidden until needed.

It'd also be nice if Quietus and Bloodspiller could turn into Living Shadow if Living Shadow is available, since you will most likely prefer to summon the shadow over a standard blood attack.

So summation:
Turn Carve and Spit/Abyssal Drain into BloodWeapon if Bloodweapon is up.
Turn Quietus and Bloodspiller into Living Shadow if Living Shadow is up.

**Comment by Grammernatzi** [comment]
Both of these are honestly not bad ideas, and they don't seem to conflict with the standard loop/opener from what I can see.

**Comment by daemitus** [comment]
added, will be available soon.
