### ISSUE TITLE
Gunbreaker's continuations

### ISSUE THREAD

**Issue by Nillinn** [daemitus/XIVComboPlugin#54]
Is it possible to make something like this option, but making Burst Strike become both kinds of Continuation moves? For Burst Strike itself and for the Gnashing Fang combo? For example, while the Gnashing Fang combo is active, Burst Strike turns into the Gnashing Fang's Continuation moves.

I think it would be a nice feature to have, since using Burst Strike cancels the Gnashing Fang combo's Continuation moves anyway, so you don't need both in your hotbar at the same time.

![Captura de tela 2021-12-23 172302](https://user-images.githubusercontent.com/94562218/147288579-27ce4f79-e2aa-4dd6-9d33-7c1b661985d1.png)

**Comment by daemitus** [comment]
fang already turns into its own continuation, and the new one makes burst turn into its own. 

Yes it would be possible to do, however I do not forsee it happening, not without some sort of customizable diy combo rework.
