### ISSUE TITLE
Kardia into Soteria enabled by default, not toggleable.

### ISSUE THREAD

**Issue by hmm-norah** [daemitus/XIVComboPlugin#56]
I recognize that there's no point in ever using Soteria without having put Kardia up first, but I wanted to raise this potential bug since it's not displayed anywhere in the plugin UI, and there are still reasons to want a dedicated Kardia button.

**Comment by daemitus** [comment]
Oops, that's missing it's config option

**Comment by daemitus** [comment]
fix coming down the pipe shortly
