### ISSUE TITLE
Reaper 1.3.0.34 Shadow Gibbet Feature

### ISSUE THREAD

**Issue by dvdio** [daemitus/XIVComboPlugin#57]
Since the last patch, Shadow Gibbet Feature stopped working, but Shadow Gallows Feature works
Also N93 Scythe Lemure's Feature says in the description that replace infernal slice instead of Nightmare Scythe
N94 same thing as N93

**Comment by daemitus** [comment]
thank you, fixed the description and identified why shadow was broken. give it a few minutes, the `.36` version will be available and you can test the fix.

**Comment by dvdio** [comment]
Testing others option for the sake of testing:
n95 Enhanced Soul Reaver Feature: does not work
n96 Enhanced Enshrouded Feature: does not work
n97 Lemure's Soul Reaver Feature: it works
n98 Communio Soul Reaver Feature: it works
n99 Enshroud Enhanced Feature: it does not work for the first ability (not change), but works after you start the combo somewhere else
n100 Enshroud Lemure's Feature: it works
n101 Enshroud Communio Feature: it works

In my opinion, n 95, 96, 97, 98 could be removed as feature, since they are useless buttons by themself when not in soul reaver, and becomes redundant with the previous options which allows for a better flow.
n 99, 100, 101 becomes redundant as well with the previous way better option that you provided.

This is the flow with the previous option
Slice ->(SoulR) Gallows -> (Ensh) Void Reaping
Shadow of death -> (SoulR) Gibbet -> (Ensh) Cross Reaping

This is the flow with the n95-98, which double the binds for no reason since you cannot slice/shadow during either SoulR or Ensh
Slice -> x
Gallows -> (Ensh) Void Reaping
Shadow of death -> x
Gibbet -> (Ensh) Cross Reaping

**Comment by daemitus** [comment]
It would help if I actually implemented n95-96. Didn't copy paste it. reviewing the other comments.

**Comment by daemitus** [comment]
ok. Im ripping out the dumb enshrouded stuff. Leaving Enshrouded->Communio as a simple replacement.

The soul reaver stuff is definitely obsolete if you just stuff it all on slice/shadow. It's definitely my preference. If for whatever reason someone wants to have a separate button for gibbet/gallows, they can use those. new version coming down the pipe shortly
