### ISSUE TITLE
BLM - Fire 1/3 feasure separation

### ISSUE THREAD

**Issue by DenL** [daemitus/XIVComboPlugin#58]
Hello, is it possible to separate the feature

"Fire 1 becomes Fire 3 outside of Astral Fire, and when FIrestarter proc is up"

into two:

"Fire 1 becomes Fire 3 outside of Astral Fire"
and
"Fire 1 becomes Fire 3 when Firestarter proc is up"?

Would love to be able to toggle them separately, thanks!

**Comment by DenL** [comment]
i want to be able to manual manage fire 1 and fire 3 usage in the overworld etc when it's not constant single target dps, with the only exception when spamming fire 1 and not having to watch for firestarter procs

**Comment by DenL** [comment]
Want to add a more concise reason for this request. Manually casting Fire/Blizzard 1/3 is one part of the gameplay that I enjoy and would like to retain that if possible.

However, watching for Firestarter procs at the last 0.5 second of every Fire 1 cast is not at all enjoyable. If you delay using a proc you risk it getting overwritten by a new proc, and if your reaction delays you risk clipping. I hate this part of BLM and really appreciate the Firestarter -> Fire 3 part of the feature.

Thus if possible, being able to toggle the two parts of the feature separately would be really great, thank you!

**Comment by daemitus** [comment]
added an option where firestarter does not switch fire1 anymore.  (soon)

**Comment by DenL** [comment]
But but I do want Firestarter to switch fire 1. I don’t want being outside of astral fire to switch fire 1.

**Comment by daemitus** [comment]
misunderstood, ill fix it in the morning before pushing it
