### ISSUE TITLE
RPR Issues with latest push

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#59]
`Shadow of Death` doesn't work with the `Gibbet` feature.  I believe the issue is the [conditional wrapping that section](https://github.com/daemitus/XIVComboPlugin/commit/d14ac329dcb9254e8330f070b9dfae1762849113#diff-c9b7d4dc02ad4a16ba2168873ae8411f4427a623a4202fe37f4cd682abfe6110R227), which only checks for the `Gallows` feature being enabled.

Unrelated, the [`Scythe Lemure's Feature`](https://github.com/daemitus/XIVComboPlugin/commit/d14ac329dcb9254e8330f070b9dfae1762849113#diff-c1c7d0c6f910fd1fbb088b0cce664437d590d0263fc931a66d0120c590febfddR442) incorrectly references Infernal Slice and `Lemure's Slice`, rather than `Nightmare Scythe` and `Lemure's Scythe`.

**Comment by daemitus** [comment]
still in "1.3.0.36"?

**Comment by kaedys** [comment]
Was still on .34, so I'll test it again.  Quite probably not, as it sounds like you already caught the issue.

**Comment by kaedys** [comment]
Nope, fixed, you beat me to it.  GW!
