### ISSUE TITLE
RDM Acceleration/Swiftcast request

### ISSUE THREAD

**Issue by Cadwgan** [daemitus/XIVComboPlugin#61]
In the spirit of combining multiple buttons with similar functionality, would it be possible to replace Acceleration with Swiftcast when:

Zero charges of Acceleration are available.
Both single target procs are up and Swiftcast is off cooldown.
Synced lower than the level for Acceleration.

Optional separate checkbox: Replace with (Enhanced) Reprise when neither are available, as a last ditch ability to keep the GCD rolling.

**Comment by kaedys** [comment]
I like the Swiftcast replacement idea.  It's useful, and I'm basically _always_ in favor of level-sync downgrades designed to avoid disrupting muscle memory.

However, it's worth noting that Enchanted Reprise is _very_ bad now, even relative to Shadowbringers (when it was "bad, but occasionally worth using").  Its mana cost is still 5/5, despite all other mana costs and generations being cut by ~40%.  Its potency was increased by 10% (300 -> 330), but that was offset by an overall increase to both our filler spell potencies and our melee combo potency (via the addition of Resolution).  In addition, its GCD was also increase by 13.6%, making its direct potency per second lower, _plus_ the fact that its mana cost is, in essence, roughly 60% more of loss than it was before.  I'm not sure falling back from Acceleration to Enchanted Reprise is a good combo to have, as it would seem to suggest that Enchanted Reprise is worth using, when it is actually more of a emergency-plan-Z type thing (especially given how mobile RDM is innately).

**Comment by PrincessRTFM** [comment]
Reasons to use (or not use) Enchanted Reprise aside, why would Acceleration change to such a completely different action? At least with Swiftcast they both do _close enough_ to the same thing for the intended use that it can still work. EnchReprise isn't a cast speeder of any kind, or even a buff, it's an _attack_. Why would you put it onto a _cast speeder buff_ action?

**Comment by Cadwgan** [comment]
Was thinking along the lines of Acceleration and Swiftcast are used mainly when you have no option but to move now, Enchanted Reprise fills that role still even if it is considered an absolute last resort now.

**Comment by kaedys** [comment]
Except they _aren't_ just used for movement.  They're also used for rotational realignment, and general potency throughput.  If you're _only_ using them for movement, you're throwing away DPS.

**Comment by kaedys** [comment]
Also, more directly, both Acceleration and Swiftcast are oGCD, while Enchanted Reprise is a GCD.

**Comment by Cadwgan** [comment]
You may be misreading what I'm requesting.

Acceleration switches to Swiftcast when you either have no charges of Acceleration left or have both procs available (and Swiftcast is up, otherwise stay as Acceleration), only switch to Reprise when you have neither Acceleration or Swiftcast available.

If you didn't plan on hitting reprise with neither up and let the GCD idle then you just don't hit the button.

**Comment by kaedys** [comment]
But that then risks you trying to use Accel, not realizing you're out of stacks, purely for DPS rather than movement, and then accidentally using Enchanted Reprise and dropping a big chunk of potency on the ground for no reason.

I just don't see a need for it.

**Comment by kaedys** [comment]
Basically, Enchanted Reprise isn't a valid fallback version of Acceleration all of its major use case situations.  It's only a fallback in some of them, and is _very very bad_ in the others.

**Comment by Cadwgan** [comment]
Never mind, I see my point is not getting across, also note I asked for it to be optional, as in it could be a separate checkbox, you don't have to use it.

The idea was to combine the keys that allow more movement as needed, if you're not tracking acceleration charges for DPS and mashing the key when both it and swiftcast are on cooldown then that's on the user.

**Comment by kaedys** [comment]
I mean, I feel like if you're not bothering to track Acceleration CD for DPS, why do you care if you keep your GCD rolling with Enchanted Reprise?  Just move and then start DPSing again when you get there.

**Comment by Cadwgan** [comment]
Okay, with what has been argued:

Acceleration switches to Swiftcast when:

No Acceleration charges are available OR
(Both procs are available AND Swiftcast available) OR
(Lower proc is available AND higher mana spell would unbalance mana AND swiftcast is available)

Reprise switches to Acceleration by default and follows the above logic, falls back to Reprise when both Acceleration and Swiftcast are on cooldown. Keeping it as a separate key to prevent accidental usage.

**Comment by kaedys** [comment]
I think I'd actually be ok with that version.  I'm still not a fan of habituating the confusion of Acceleration and Reprise, but there's basically never a situation where you'd _prefer_ to sit on an Acceleration/Swiftcast charge and use Reprise instead.  So replacing Reprise, rather than the other direction, seems fine to me.  Superceding, rather than falling back, if that makes sense.

Basically, it's not the case that every usage of an Acceleration could be approximated by a usage of Reprise.  However, it _is_ the case that any usage of Reprise would be better spent on Acceleration (or failing that, Swiftcast) -> Verthunder/Veraero.

**Comment by Grammernatzi** [comment]
As someone with RDM 90, the optimal way to have it is just simply that Acceleration is replaced by Swiftcast if Acceleration's cooldown is rolling and Swiftcast's is not. You want to make sure both are rolling at all times since they are both DPS cooldowns, and if Swiftcast is off-cooldown, it's the priority. Don't really need any more logic than that to it, to be honest; it's just overthinking it.

**Comment by daemitus** [comment]
The stupid bug from comparing things with charges to things not with
charges prevents me from implementing this at the moment. I'll circle back
to it eventually.

**Comment by daemitus** [comment]
this will be in soon.
