### ISSUE TITLE
[RPR] Alternative for Shadow Gallows/Gibbet

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#62]
Can we get an additional option to have a Gibbet/Gallows override on Soul Slice instead of/as well as Shadow of Death?  Soul Slice is not usable when Enshrouded, and you _never_ want to use it when you have Soul Reaving stacks (since it discards them, same as using any attack).  Shadow of Death, on the other hand, _is_ usable when Enshrouded, and many advanced openers and 2-minute windows include using it during Enshroud to extend the duration of the buff to squeeze in two of them in a burst window (it's used to circumvent the 15s cooldown restriction on it, you pop Enshroud, but instead of using your Reaping abilities immediately, you weave two Shadow of Death casts at the start so that the Communio occurs 5s later than otherwise, during the raid buffs).  If we had an option to place Gibbet or Gallows (and by extension, the relevant Reaping skill during Enshroud) on Soul Slice instead, it would allow us to still merge Gibbet/Gallows into our "normal" ability set, while retaining the ability to use Shadow of Death during Enshroud.

Edit: this would also probably need an equivalent to the Shadow Lemure and Shadow Communio features as well.

**Comment by kaedys** [comment]
In the spirit of helping out, and because I was bored at 2 AM (=P), I decided to make a stab at writing the changes myself.  Do note, as I mentioned in the PR, C# is _not_ my primary language, and it's been years since I last touched the language (and even then, I was decidedly in the "amateur" category).  So that PR may have mistakes or bugs.  Please review it closely before merging, or instead use it as a base for your own version of the changes if you prefer.

**Comment by daemitus** [comment]
done
