### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by nyxalteria** [daemitus/XIVComboPlugin#64]
Not sure what happened but within the past 24 hours or so I've started crashing when hitting "log out and return to title screen" another user has also reported this error. I did some testing and installed plugins and deinstalled them one at a time, this one is the one that seemed to be causing the crashes. There's no crash error, the game just kills itself. It's not 100% of the time but it happens maybe 50% of the time. 

edit: thinking it has to do with one of these 4 commits cause it wasn't happening at all before those 

![image](https://user-images.githubusercontent.com/92659516/147381238-d76163bd-a5ed-40b3-8eba-dc89b4dfca2c.png)

**Comment by daemitus** [comment]
any job in particular

**Comment by daemitus** [comment]
nevermind, i already identified it :|

**Comment by daemitus** [comment]
please let me know if it happens against after you upgprade to `.38`
