### ISSUE TITLE
[RDM] Small glitch with verfire/verstone icon

### ISSUE THREAD

**Issue by 0kie** [daemitus/XIVComboPlugin#68]
If you log off as a red mage, the next time you log in verfire/verstone icon will not change to verthunder III/veraero III, jolt or verholy/verflare. 
The combo will still work normally and the other combos' icons like aoe combo or redoublement combo will still work normally, just verfire/verstone will not be changing icons.

Simply changing jobs and then back to red mage makes the icon change works again.

**Comment by Grammernatzi** [comment]
Do you have any other XIVCombo plugins installed? I've not noticed this issue and I play a lot of Red Mage. I've had people mention stuff like this before but they had other XIVCombo forks running, and it's worth noting you can only have one enabled at a time without having issues.

**Comment by 0kie** [comment]
only this fork is installed, but I did use some other forks in the past, could be some old config file or something like that.
I would also like to note that it doesn't happen 100% all the time I log off/log in as a red mage

**Comment by daemitus** [comment]
probably a dalamud caching issue if anything. i can't imagine theres anything that can be done on our end. 

If you can figure anything else out about it, please re-open or make a new ticket.
