### ISSUE TITLE
[DNC] Single Target Multibutton

### ISSUE THREAD

**Issue by Mishiko233** [daemitus/XIVComboPlugin#72]
The way Single Target Multibutton is setup at the moment, it prioritizes Reverse Cascade over Fountainfall whenever the player uses Flourish. This is not optimal and ends up causing for a loss in overall damage. Is there a possibility that the priority order between Reverse Cascade and Fountainfall, ONLY after Flourish usage, is swapped? Thanks in advance.

**Comment by daemitus** [comment]
how does it work out to be a potency loss? I don't do end-game dancer, but
generally, have proc = use proc?

**Comment by Mishiko233** [comment]
During a typical opener, you use 3 GCD's, 2 of them being Starfall and Tilapia, before going into Standard Step. Given that you use Flourish, in the very starting opener, 75-80% of times, during Party Finder, you won't manage to get enough Esprit to pull a Saber Dance off, leaving you to the choice of either Reverse Cascade or Fountainfall. In this scenario, and in general a simpler scenario too, if both choices are available, one would always want to go for Fountainfall over Reverse Cascade, as it has 60 extra potency.

**Comment by Mishiko233** [comment]
But by any means, my "math" or "theory" might not be 100%, it's just something that makes sense in my mind. Please correct me if i'm incorrect. In any case, i end up learning more.

**Comment by daemitus** [comment]
done. flow is prioritized over symmetry.

**Comment by Mishiko233** [comment]
Thank you sir!
