### ISSUE TITLE
[NIN] Patch 6.05 changes

### ISSUE THREAD

**Issue by dvdio** [daemitus/XIVComboPlugin#73]
n68 **Bunshin / Kamaitachi Feature**: is no longer necessary, they implemented it.

n69,70,71: Since they changed Forked and Fleeting Raiju, i might suggest:
**Fleeting Raiju** on the **Armor Crush** and **Aeolian Edge**, when the **_Raiju Ready_** buff is up (they changed the name of the buff).
For **Forked Raiju** which is now a gap closer, maybe on the **Huraijin**? since it is for specific situations as that.

Great work as always, dont rush anything and be sure to enjoy the game first, happy new year.

**Comment by Grammernatzi** [comment]
I already made these changes in my own fork for Dae to use, so he can easily add it when he wakes up. I also thought of maybe making Armor Crush forked too, since I feel most people won't have Huraijin centered around their main actions.

**Comment by daemitus** [comment]
these will be implemented soon.
