### ISSUE TITLE
[NIN] Option for combo/armor crush to change to Fleeting Raiju

### ISSUE THREAD

**Issue by perks** [daemitus/XIVComboPlugin#76]
Now that ninja raiton gives branching choices between gap closer (Forked Raiju) and melee attack (Fleeting Raiju), add option to use melee attack so you don't gap close meme.

Raiju is no longer a combo so its an either/or choice of the 1 skill (no more two procs)

**Comment by daemitus** [comment]
been doing maps, i hope to have this out tonight.
