### ISSUE TITLE
Ninja Huraijin to Armor Crush after Gust Slash suggestion

### ISSUE THREAD

**Issue by Nillinn** [daemitus/XIVComboPlugin#77]
Huraijin becomes Armor Crush after Gust Slash is used.

Both Ninja combos are 1-2-3 (Spinning Slash -> Gust Slash -> Either Aeolian Edge or Armor Crush)

So right after Gust Slash, the Huraijin could turn into Armor Crush. And then, if you use a combo finisher or the combo just ends, it goes back to being Huraijin.

Huraijin is pretty much an Armor Crush that you use to recover huton after a death
Both armor crush and huraijin do the same thing, but one is used outside of a combo, so they could be a single button.

**Comment by Grammernatzi** [comment]
This actually seems like a pretty good idea and would have the bonus of saving an additional button. I like the thinking behind it.

**Comment by daemitus** [comment]
added. will be available soon.
