### ISSUE TITLE
Armor Crush to Ninjutsu feature suggestion

### ISSUE THREAD

**Issue by Nillinn** [daemitus/XIVComboPlugin#78]
Pretty much the image below, but with Armor Crush, because it is used less than aeolian edge.

![Captura de tela 2022-01-05 182809](https://user-images.githubusercontent.com/94562218/148292040-ad136448-d447-4016-b869-a3c6dbba8f37.png)

Edit: I just tested the feature above and it doesn't seem to be working by the way (The GCDs to ninjutsu option is working tho)

**Comment by Grammernatzi** [comment]
I mean, does it matter which is less used? You can't use any gcds while you're using ninjutsu or you will get a bunny.

**Comment by daemitus** [comment]
i agree with grammer, but done. available soon.
