### ISSUE TITLE
Verproc into jolt opener fault

### ISSUE THREAD

**Issue by junp3i** [daemitus/XIVComboPlugin#8]
On Red Mage "verproc into jolt plus opener feature" is also changing jolt into Veraero , not just the verthunder.

Thanks!

**Comment by daemitus** [comment]
jolt/jolt2 stays as jolt2. ive split the opener feature into a stone and fire version. So you can have atleast one jolt in addition to the longcast opener spell.

Otherwise, as you describe it I could not reproduce. Feel free to contact me if you continue to have problems.
