### ISSUE TITLE
Scholar Suggestions

### ISSUE THREAD

**Issue by Lunatory** [daemitus/XIVComboPlugin#81]
1: Change Summon Eos/Selene to Summon Seraph while a faerie is active.
2: Change Whispering Dawn/Fey Illumination to Summon Eos/Selene while no faerie is active (and Seraph isn't summoned).
3: Change Recitation to Excogitation when Recitation is on Cooldown.

**Comment by Lunatory** [comment]
In 2 "While no Faerie is active" does not refer to a lack of faeries due to Seraph being summoned.

**Comment by daemitus** [comment]
1. done.
2. necessary with 1? Grammer showed me a pic once, and it looks really really silly with 10 summon eos/carbuncle things.
3. for convienence?

**Comment by lhn1703** [comment]
Combine excogitation and lustrate like the sage taurochole to druochole variant.

**Comment by Lunatory** [comment]
2 is seemingly obsolete if 1 is implemented. It was more of an either or deal.
3 is indeed for convenience. I will often use my recitation on excogitation and can not think of a single instance where I would want to go out of my way to *not* use a recitated excog where both are off cooldown.

**Comment by daemitus** [comment]
@lhn1703 excog when off CD, otherwise lustrate?

@Lunatory 3 added soon.

**Comment by lhn1703** [comment]
Yes, excog is basically stronger lustrate with trigger conditions.

**Comment by daemitus** [comment]
done
