### ISSUE TITLE
[BUG] Program hard freezes when enabling child feature

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#85]
In this case, I was selecting the Mythril Tempest Inner Release feature.  Selecting it froze FFXIV and registered it as not responding in Task Manager.

I believe the issue is [this line](https://github.com/daemitus/XIVComboPlugin/blob/a46697ea34b73909ec3cdc2dec4540cfeed4d373/XIVComboExpanded/ConfigWindow.cs#L244).  From what I can tell, this repeatedly assigns the same value as was initially assigned (on line 230), causing an infinite loop.  I believe this line should be attempting to get the parent of either `parent` or `parentMaybe`, depending on the type expected.

**Comment by daemitus** [comment]
you are absolutely right. fix going out now., thanks!
