### ISSUE TITLE
Monk issue

### ISSUE THREAD

**Issue by doomsz** [daemitus/XIVComboPlugin#87]
Perfect Balance changing into Masterfull Blitz feature shouldnt work on < 60 lvl synced content

**Comment by Grammernatzi** [comment]
Yeah, it's missing a level check, but to be fair it's kind of understandable why it's not there. The game seemingly still gives you Beast Chakra even when you don't have the gauge unlocked. Regardless, it looks like a rather simple fix.

**Comment by doomsz** [comment]
as expected from indie company :D
