### ISSUE TITLE
Suggestion: Ability to check Charges

### ISSUE THREAD

**Issue by Rubylium** [daemitus/XIVComboPlugin#88]
Unless I didn't see it in the code, I don't think there is a way to check Charges for a skill (for example Bloodletter in bard that can have 3 Charge). I tried making combo with it is using ``IsOffCooldown`` but when it is loading a charge it do count that as a slowdown even if there is still charges available.

Having a function to check if an ability has charge remaining could be very helpful, if it is possible :)Thanks!

**Comment by Grammernatzi** [comment]
This was added a while ago, you can check charges on a cooldown if you use GetCooldown.

**Comment by Rubylium** [comment]
Aah didn't pull my repo for a while didn't see it ! Thanks

**Comment by Rubylium** [comment]
I see now that FFXIVClientStructs got added, got an error on it as i suppose i don't have it on my project. What exaclty should i add ?

![image](https://user-images.githubusercontent.com/19718604/149508070-df823db4-8643-4573-a41d-b5710f3c5ae3.png)
![image](https://user-images.githubusercontent.com/19718604/149508091-ce3acaf4-e854-451a-b493-d267c9af45ee.png)

**Comment by Grammernatzi** [comment]
You need to download the FFXIVClientStructs project from the link in the files on github, and extract it to the lib folder.
