### ISSUE TITLE
[RDM] Swiftcast -> Acceleration

### ISSUE THREAD

**Issue by Zynyx** [daemitus/XIVComboPlugin#90]
Hello. :) Can make a macro that already kinda does it-- but for a QoL sanity thing... Could you make it so when Swiftcast is up, you cast that before you cast Acceleration from the ability bar?

It'd make it a bit easier to line up GCDs for openers and RDM can always insta rez with Vercure anyway.

Thanks!

**Comment by Zynyx** [comment]
Apparently this is already in the latest version.... So nevermind. :) Ty.!

**Comment by daemitus** [comment]
are you sure?

**Comment by Zynyx** [comment]
Yep, I noticed my version was out of date... Updated it and there it was.
