### ISSUE TITLE
Machinist Overdrive Feature

### ISSUE THREAD

**Issue by Nillinn** [daemitus/XIVComboPlugin#91]
Hi, is this feature supposed to work with the Automaton Queen as well, since it replaces the Rook Autoturret after lv80?
If not, would it be possible to add it to the Automaton Queen and her 2 Overdrive moves? (Pile Bunker and Crowned Collider)
![image](https://user-images.githubusercontent.com/94562218/149671495-597b3eb9-87bf-4a60-af30-42aec807a552.png)
![image](https://user-images.githubusercontent.com/94562218/149671586-016d45ef-7d1c-41e3-889f-2e280a564b81.png)

**Comment by daemitus** [comment]
if you drag rook onto your bar, it should take care of it. Collider is used
automatically after using overdrive/bunker.

**Comment by Nillinn** [comment]
Oh ok thank you. Dragging rook onto the bar solved it
