### ISSUE TITLE
BLM possible mix up

### ISSUE THREAD

**Issue by Samidaro** [daemitus/XIVComboPlugin#92]
since the update today on BLM: blizzard 1 does not turn into 3 when outside of umbral ice (it just stays blizzard 3) meanwhile blizzard 4 turns into fire and blizzard 1 randomly.  i don't know what i did  anymore

**Comment by daemitus** [comment]
I'll look into it now

**Comment by Samidaro** [comment]
ok, i have the blizzard 1 into 3 and the blizz4/fire4 options active

**Comment by daemitus** [comment]
So I probably need to change the wording, is there a reason to actually use bliz1 once you have bliz3?

**Comment by Samidaro** [comment]
i don't think so. It was mostly for lower levels. But i can get used to it.

**Comment by daemitus** [comment]
It should switch back to bliz1 if you're under 35.

enochian feature, aka fire4/bliz4 works for me. Can you try reinstalling the plugin? They should only switch to fire1/bliz1 if you're under 60 and 58 respectively.

**Comment by Samidaro** [comment]
ok let me reinstall. Only thing that changes really is: before blizz 3 would become 1 at low levels. Not it's blizz 4 that changes. not a big deal

**Comment by daemitus** [comment]
Should be both

**Comment by daemitus** [comment]
You may need to drag it back on your bar or switch zones

**Comment by Samidaro** [comment]
yeah, but 3 isn't changing for me :( anyway enochian works now so that just required a reinstall

**Comment by daemitus** [comment]
try dragging bliz1 onto your bar, then hop into your fc house. its
typically what i need to do to get the bars to update properly.

**Comment by Samidaro** [comment]
ok, now blizz 1 is changing into blizz 3 when out of umbral. However it doesn't change back to 1 when in umbral.

**Comment by daemitus** [comment]
is it desirable to use bliz1 in umbral? From what I can tell everything's the same, 0mp, same cast-time, just more damage in bliz3.

**Comment by Samidaro** [comment]
now that you mention it...no. I just got used to that option in the addon i guess. I'm a moron ahahah

**Comment by daemitus** [comment]
no problem :D 

Let me know if you have any other issues. I pulled in a bunch of BLM stuff Grammer had brewing and could use the feedback if I missed anything.

**Comment by Samidaro** [comment]
thanks a lot. Sorry for wasting time

**Comment by Samidaro** [comment]
on another notice, since i'm a massive annoyance. Reckon we could split the enochian feature into one that does only blizz4/fire4 and another further one for the fire 1 and blizz 1. I'd like to use only the first part

**Comment by daemitus** [comment]
remove the level syncing part?

**Comment by Samidaro** [comment]
yeah, or have it as separate.

**Comment by daemitus** [comment]
done

**Comment by Samidaro** [comment]
That's amazing, thanks again
