### ISSUE TITLE
Monk AoE Combo

### ISSUE THREAD

**Issue by Samidaro** [daemitus/XIVComboPlugin#93]
With the new Masterful Blitz to aoe combo option, when under perfect balance, the whole combo is  Four-Point Fury. Works perfect without perfect balance. There was an option before that would try to suggest the missing combo for the missing Solar or Lunar Nadi. Was just wondering if it could be fused together. Thanks/Sorry again ;p

**Comment by daemitus** [comment]
imma make a guess that you're on dalamud testing

**Comment by daemitus** [comment]
this should be fixed. i pre-emptively made a change and the new dalamud hasn't been pushed yet.

**Comment by Samidaro** [comment]
That's perfect now. Thanks again
