### ISSUE TITLE
[RPR] Split Regress feature on Ingress and Egress 

### ISSUE THREAD

**Issue by kaedys** [daemitus/XIVComboPlugin#94]
I'm very used to using Ingress as my "get out of bad free" card.  I have the Regress feature disabled, because when I'm panic-spamming Ingress, it's fairly common for me to accidentally double-tap it and teleport right back into bad.  I've gotten used to my Ingress button being the "GTFO" and shift-Ingress-button being "go back in afterward".

However, that gets upended when I do use Egress.  Because I have the Regress feature disabled, when I use Egress (which I almost always use as a proper disengage, without the panic-spam), my "go back in" button is now Ingress.  So what I'd like to ask for is to have is the Ingress and Egress -> Regress feature split, so I can only enable it on Egress.  Basically, Ingress would only turn into Regress if I Egressed first, but Egress would _always_ turn back into Regress, so my muscle memory from Ingress still works when I use Egress.

Alternatively (not sure how possible this would be) or potentially in addition, an option to add a slight delay (1-1.5s) after the teleport before it becomes Regress, to avoid the Teleport spam -> Regress -> dead issue.  This could probably be done based on the remaining duration on the `Threshold` buff, since it lasts for 10s from the initial teleport (and thus only changes the action when it's <8.5s or similar).

**Comment by Grammernatzi** [comment]
The optional delay seems like the best solution for me. It would be very easy to check just by tracking the buff duration.

**Comment by daemitus** [comment]
The delayed 8.5s option will be available soon. Due to how things work, this only applies to the action that was used. The other will immediately transform into Regress.
